variable_mappings= [
    {'A001': 'Important in life: Family'},
{'A002': 'Important in life: Friends'},
{'A003': 'Important in life: Leisure time'},
{'A004': 'Important in life: Politics'},
{'A005': 'Important in life: Work'},
{'A006': 'Important in life: Religion'},
{'A007': 'Important in life: Service to others'},
{'A008': 'Feeling of happiness'},
{'A009': 'State of health (subjective)'},
{'A010': 'Ever felt very excited or interested'},
{'A011': 'Ever felt restless'},
{'A012': 'Ever felt proud because someone complimented you'},
{'A013': 'Ever felt very lonely or remote from other people'},
{'A014': 'Ever felt pleased about having accomplished something'},
{'A015': 'Ever felt bored'},
{'A016': 'Ever felt on top of the world'},
{'A017': 'Ever felt depressed or very unhappy'},
{'A018': 'Ever felt that things were going your way'},
{'A019': 'Ever felt upset because somebody criticized you'},
{'A025': 'Respect and love for parents'},
{'A026': 'Parents responsibilities to their children'},
{'A027': 'Important child qualities: Good manners'},
{'A029': 'Important child qualities: independence'},
{'A030': 'Important child qualities: Hard work'},
{'A032': 'Important child qualities: feeling of responsibility'},
{'A034': 'Important child qualities: imagination'},
{'A035': 'Important child qualities: tolerance and respect for other people'},
{'A038': 'Important child qualities: thrift saving money and things'},
{'A039': 'Important child qualities: determination perseverance'},
{'A040': 'Important child qualities: religious faith'},
{'A041': 'Important child qualities: unselfishness'},
{'A042': 'Important child qualities: obedience'},
{'A043B': 'Important child qualities: Self-expression'},
{'A044': 'What children should learn 1'},
{'A045': 'What children should learn 2'},
{'A046': 'Abortion when the mothers health is at risk'},
{'A047': 'Abortion when child physically handicapped'},
{'A048': 'Abortion when woman not married'},
{'A049': 'Abortion if not wanting more children'},
{'A057': 'Spend time with parents or other relatives'},
{'A058': 'Spend time with friends'},
{'A059': 'Spend time with colleagues from work'},
{'A060': 'Spend time with people at your church, mosque or synagogue'},
{'A061': 'Spend time with people at sport, culture, communal organization'},
{'A062': 'How often discusses political matters with friends'},
{'A063': 'Persuading friends, relatives or fellow workers'},
{'A064': 'Member: Belong to social welfare service for elderly'},
{'A065': 'Member: Belong to religious organization'},
{'A066': 'Member: Belong to education, arts, music or cultural activities'},
{'A067': 'Member: Belong to labour unions'},
{'A068': 'Member: Belong to political parties'},
{'A069': 'Member: Belong to local political actions'},
{'A070': 'Member: Belong to human rights'},
{'A071': 'Member: Belong to conservation, the environment, ecology, animal rights'},
{'A071B': 'Member: Belong to conservation, the environment, ecology'},
{'A071C': 'Member: Belong to animal rights'},
{'A072': 'Member: Belong to professional associations'},
{'A073': 'Member: Belong to youth work'},
{'A074': 'Member: Belong to sports or recreation'},
{'A075': 'Member: Belong to women�s group'},
{'A076': 'Member: Belong to peace movement'},
{'A077': 'Member: Belong to organization concerned with health'},
{'A078': 'Belong: Consumer groups'},
{'A079': 'Member: Belong to other groups'},
{'A080': 'Member: Belong to none'},
{'A080_01': 'Member: Humanitarian or charitable organization'},
{'A080_02': 'Member:  Self-help group, mutual aid group'},
{'A081': 'Voluntary work: Unpaid work social welfare service for elderly, handicapped or deprived people'},
{'A082': 'Voluntary work: Unpaid work religious or church organization'},
{'A083': 'Voluntary work: Unpaid work education, arts, music or cultural activities'},
{'A084': 'Voluntary work: Unpaid work labour unions'},
{'A085': 'Voluntary work: Unpaid work political parties or groups'},
{'A086': 'Voluntary work: Unpaid work local political action groups'},
{'A087': 'Voluntary work: Unpaid work human rights'},
{'A088': 'Voluntary work: Unpaid work environment, conservation, animal rights'},
{'A088B': 'Voluntary work: Unpaid work environment, conservation, ecology'},
{'A088C': 'Voluntary work: Unpaid work animal rights'},
{'A089': 'Voluntary work: Unpaid work professional associations'},
{'A090': 'Voluntary work: Unpaid work youth work'},
{'A091': 'Voluntary work: Unpaid work sports or recreation'},
{'A092': 'Voluntary work: Unpaid work women�s group'},
{'A093': 'Voluntary work: Unpaid work peace movement'},
{'A094': 'Voluntary work: Unpaid work organization concerned with health'},
{'A096': 'Voluntary work: Unpaid work other groups'},
{'A097': 'Voluntary work: Unpaid work none'},
{'A098': 'Active/Inactive membership of church or religious organization'},
{'A099': 'Active/Inactive membership of sport or recreation'},
{'A100': 'Active/Inactive membership of art, music, educational'},
{'A101': 'Active/Inactive membership of labour unions'},
{'A102': 'Active/Inactive membership of political party'},
{'A103': 'Active/Inactive membership of environmental organization'},
{'A104': 'Active/Inactive membership of professional organization'},
{'A105': 'Active/Inactive membership of charitable/humanitarian organization'},
{'A106': 'Active/Inactive membership of any other organization'},
{'A106B': 'Active/Inactive membership: Consumer organization'},
{'A106C': 'Active/Inactive membership: Self-help group, mutual aid group'},
{'A106D': 'Active/Inactive membership: Women�s group'},
{'A107': 'Reasons voluntary work: Solidarity with the poor and disadvantaged'},
{'A108': 'Reasons voluntary work: Compassion for those in need'},
{'A109': 'Reasons voluntary work: Opportunity to repay something'},
{'A110': 'Reasons voluntary work: Sense of duty, moral, obligation'},
{'A111': 'Reasons voluntary work: Identifying with people who suffer'},
{'A112': 'Reasons voluntary work: Time on my hands'},
{'A113': 'Reasons voluntary work: Personal satisfaction'},
{'A114': 'Reasons voluntary work: Religious belief'},
{'A115': 'Reasons voluntary work: Help disadvantaged people'},
{'A116': 'Reasons voluntary work: Make a contribution to my local community'},
{'A117': 'Reasons voluntary work: Bring about social or political change'},
{'A118': 'Reasons voluntary work: For social reasons'},
{'A119': 'Reasons voluntary work: Gain new skills and useful experience'},
{'A120': 'Reasons voluntary work: Did not want to, but could not refuse'},
{'A124_01': 'Neighbours: People with a criminal record'},
{'A124_02': 'Neighbours: People of a different race'},
{'A124_03': 'Neighbours: Heavy drinkers'},
{'A124_04': 'Neighbours: Emotionally unstable people'},
{'A124_05': 'Neighbours: Muslims'},
{'A124_06': 'Neighbours: Immigrants/foreign workers'},
{'A124_07': 'Neighbours: People who have AIDS'},
{'A124_08': 'Neighbours: Drug addicts'},
{'A124_09': 'Neighbours: Homosexuals'},
{'A124_10': 'Neighbours: Jews'},
{'A124_11': 'Neighbours: Evangelists'},
{'A124_12': 'Neighbours: People of a different religion'},
{'A124_13': 'Neighbours: People of the same religion'},
{'A124_14': 'Neighbours: Militant minority'},
{'A124_15': 'Neighbours: Zoroastrians'},
{'A124_16': 'Neighbours: People not from country of origin'},
{'A124_17': 'Neighbours: Gypsies'},
{'A124_18': 'Neighbours: Political Extremists'},
{'A124_19': 'Neighbours: Trafficants'},
{'A124_20': 'Neighbours: Indians or Lebanese'},
{'A124_21': 'Neighbours: Chinese or Philippino Chinese'},
{'A124_22': 'Neighbours: Spiritists'},
{'A124_23': 'Neighbours: Protestants'},
{'A124_24': 'Neighbours: Christians'},
{'A124_25': 'Neighbours: Witchdoctors and related labels'},
{'A124_27': 'Neighbours: Right wing extremists'},
{'A124_28': 'Neighbours: People with large families'},
{'A124_29': 'Neighbours: Hindus'},
{'A124_30': 'Neighbours: North-American persons'},
{'A124_31': 'Neighbours: Haitians'},
{'A124_32': 'Neighbours: Members of new religious movements'},
{'A124_33': 'Neighbours: Jews, Arabs, Asians, gypsies, etc'},
{'A124_34': 'Neighbours: Black people'},
{'A124_35': 'Neighbours: White people'},
{'A124_36': 'Neighbours: Coloured people'},
{'A124_37': 'Neighbours: Indians'},
{'A124_38': 'Neighbours: Kurds, Esids'},
{'A124_42': 'Neighbours: Unmarried couples living together'},
{'A124_43': 'Neighbours: People who speak a different language'},
{'A124_45': 'Neighbours: Sunnis'},
{'A124_46': 'Neighbours: Shia'},
{'A124_47': 'Neighbours: French'},
{'A124_48': 'Neighbours: British'},
{'A124_49': 'Neighbours: Iranian'},
{'A124_50': 'Neighbours: Kuwaiti'},
{'A124_51': 'Neighbours: Turkish'},
{'A124_52': 'Neighbours: Jordanian'},
{'A124_53': 'Neighbours: Kildani'},
{'A124_54': 'Neighbours: Indigenes; Aborigenes'},
{'A124_55': 'Neighbours: Maori'},
{'A124_56': 'Neighbours: Pacific Islanders'},
{'A124_57': 'Neighbours: Europeans/Pakeha'},
{'A124_58': 'Neighbours: Americans'},
{'A124_59': 'Neighbours: Chaldean'},
{'A124_60': 'Neighbours: Mapuches'},
{'A124_61': 'Neighbours: Russians'},
{'A165': 'Most people can be trusted'},
{'A168': 'Do you think most people try to take advantage of you'},
{'A168A': 'Do you think most people try to take advantage of you (10 point scale)'},
{'A169': 'Good human relationships'},
{'A170': 'Satisfaction with your life'},
{'A173': 'How much freedom of choice and control'},
{'A174': 'Membership consumer organisation'},
{'A189': 'Schwartz: It is important to this person to think up new ideas and be creative'},
{'A190': 'Schwartz: It is important to this person to be rich'},
{'A191': 'Schwartz: It is important to this person living in secure surroundings'},
{'A192': 'Schwartz: It is important to this person to have a good time'},
{'A193': 'Schwartz: It is important to this person to help the people nearby'},
{'A194': 'Schwartz: It is important to this person being very successful'},
{'A195': 'Schwartz: It is important to this person adventure and taking risks'},
{'A196': 'Schwartz: It is important to this person to always behave properly'},
{'A197': 'Schwartz: It is important to this person looking after the environment'},
{'A198': 'Schwartz: It is important to this person tradition'},
{'A199': 'Schwartz: It is important to this person to do something for the good of society'},
{'A200': 'Social position: People in their 20s'},
{'A201': 'Social position: People in their 40s'},
{'A202': 'Social position: People in their 70s'},
{'A203': 'Is a 30-year old boss acceptable'},
{'A204': 'People over 70: are seen as friendly'},
{'A205': 'People over 70: are seen as competent'},
{'A206': 'People over 70: viewed with respect'},
{'A207': 'Is a 70-year old boss acceptable'},
{'A208': 'Older people are not respected much these days'},
{'A209': 'Older people get more than their fair share from the government'},
{'A210': 'Older people are a burden on society'},
{'A211': 'Companies that employ young people perform better than those that employ people of different ages'},
{'A212': 'Old people have too much political influence'},
{'A213': 'I see myself as someone who: is reserved'},
{'A214': 'I see myself as someone who: is generally trusting'},
{'A215': 'I see myself as someone who: tends to be lazy'},
{'A216': 'I see myself as someone who: is relaxed, handles stress well'},
{'A217': 'I see myself as someone who: has few artistic interests'},
{'A218': 'I see myself as someone who: is outgoing, sociable'},
{'A219': 'I see myself as someone who: tends to find fault with others'},
{'A220': 'I see myself as someone who: does a thorough job'},
{'A221': 'I see myself as someone who: gets nervous easily'},
{'A222': 'I see myself as someone who: has an active imagination'},
{'B001': 'Would give part of my income for the environment'},
{'B002': 'Increase in taxes if used to prevent environmental pollution'},
{'B003': 'Government should reduce environmental pollution'},
{'B004': 'Would buy things at a 20% higher price if it helped to protect environment'},
{'B005': 'All talk about the environment make people anxious'},
{'B006': 'Combatting unemployment, we have to accept environmental problems'},
{'B007': 'Protecting environment and fighting pollution is less urgent than suggested'},
{'B008': 'Protecting environment vs. Economic growth'},
{'B009': 'Human & nature'},
{'B010': '[Country]s environmental problems can be solved without any international agreements to handle them'},
{'B011': 'Environmental action: chosen products that are better for environment'},
{'B012': 'Environmental action: recycle'},
{'B013': 'Environmental action: reduce water consumption'},
{'B014': 'Environmental action: attend meeting, signed petition'},
{'B015': 'Environmental action: contributed to environmental organization'},
{'B016': 'Tradition vs. high economic growth'},
{'B017': 'Humanity has a bright or bleak future'},
{'B018': 'Environmental problems in your community: Poor water quality.'},
{'B019': 'Environmental problems in your community: Poor air quality.'},
{'B020': 'Environmental problems in your community: Poor sewage and sanitation.'},
{'B021': 'Environmental problems in the world: Global warming or the greenhouse effect.'},
{'B022': 'Environmental problems in the world: Loss of plant or animal species or biodiversity.'},
{'B023': 'Environmental problems in the world: Pollution of rivers, lakes and oceans.'},
{'B030': 'Past two years: given money to ecological organization'},
{'B031': 'Past two years: participated in demonstration for environment'},
{'C001': 'Jobs scarce: Men should have more right to a job than women (3 categories)'},
{'C001_01': 'Jobs scarce: Men should have more right to a job than women (5 categories)'},
{'C002': 'Jobs scarce: Employers should give priority to (nation) people than immigrants (3 categories)'},
{'C002_01': 'Jobs scarce: Employers should give priority to (nation) people than immigrants (5 categories)'},
{'C004': 'Jobs scarce: older people should be forced to retire'},
{'C005': 'Unfair to give work to handicapped people when able bodied people can�t find jobs'},
{'C006': 'Satisfaction with financial situation of household'},
{'C008': 'Work compared with Leisure'},
{'C009': 'First choice, if looking for a job'},
{'C010': 'Second choice if looking for a job'},
{'C011': 'Important in a job: good pay'},
{'C012': 'Important in a job: not too much pressure'},
{'C013': 'Important in a job: good job security'},
{'C014': 'Important in a job: a respected job'},
{'C015': 'Important in a job: good hours'},
{'C016': 'Important in a job: an opportunity to use initiative'},
{'C017': 'Important in a job: generous holidays'},
{'C018': 'Important in a job: that you can achieve something'},
{'C019': 'Important in a job: a responsible job'},
{'C020': 'Important in a job: a job that is interesting'},
{'C021': 'Important in a job: a job that meets one�s abilities'},
{'C022': 'Important in a job: pleasant people to work with'},
{'C023': 'Important in a job: good chances for promotion'},
{'C024': 'Important in a job: a useful job for society'},
{'C025': 'Important in a job: meeting people'},
{'C031': 'Degree of pride in your work'},
{'C033': 'Job satisfaction'},
{'C034': 'Freedom decision taking in job'},
{'C036': 'To develop talents you need to have a job'},
{'C037': 'Humiliating to receive money without having to work for it'},
{'C038': 'People who don�t work turn lazy'},
{'C039': 'Work is a duty towards society'},
{'C040': 'People should not have to work if they don�t want to'},
{'C041': 'Work should come first even if it means less spare time'},
{'C042B1': 'Why people work: work is like a business transaction'},
{'C042B2': 'Why people work: I do the best I can regardless of pay'},
{'C042B3': 'Why people work: I wouldn�t work if I didn�t have to'},
{'C042B4': 'Why people work: I wouldn�t work if work interfered my life'},
{'C042B5': 'Why people work: work most important in my life'},
{'C042B6': 'Why people work: I never had a paid job'},
{'C042B7': 'Why people work: don�t know'},
{'C059': 'Fairness: One secretary is paid more'},
{'C060': 'How business and industry should be managed'},
{'C061': 'Following instructions at work'},
{'C062': 'Work: until satisfied with results'},
{'C063': 'Work: accomplish personal goals'},
{'C064': 'Work: stay up late to finish'},
{'COUNTRY_ALPHA': 'ISO 3166-1 alpha-3 country code'},
{'COW_ALPHA': 'CoW country code alpha'},
{'COW_NUM': 'CoW country code numeric'},
{'D001': 'How much do you trust your family'},
{'D001_B': 'How much you trust: Your family (B)'},
{'D002': 'Satisfaction with home life'},
{'D003': 'Sharing with partner: attitudes towards religion'},
{'D004': 'Sharing with partner: moral standards'},
{'D005': 'Sharing with partner: social attitudes'},
{'D006': 'Sharing with partner: political views'},
{'D007': 'Sharing with partner: sexual attitudes'},
{'D008': 'Sharing with partner: no sharing attitudes'},
{'D009': 'Sharing with partner: don�t know or missing'},
{'D010': 'Sharing with parents: attitudes towards religion'},
{'D011': 'Sharing with parents: moral standards�'},
{'D012': 'Sharing with parents: social attitudes'},
{'D013': 'Sharing with parents: political views'},
{'D014': 'Sharing with parents: sexual attitudes'},
{'D015': 'Sharing with parents: no sharing attitudes'},
{'D016': 'Sharing with parents: don�t know or missing'},
{'D017': 'Ideal number of children'},
{'D018': 'Child needs a home with father and mother'},
{'D019': 'A woman has to have children to be fulfilled'},
{'D022': 'Marriage is an out-dated institution'},
{'D023': 'Woman as a single parent'},
{'D024': 'Enjoy sexual freedom'},
{'D025': 'If only one child allowed: boy or girl'},
{'D026_03': 'Duty towards society to have children'},
{'D026_05': 'It is childs duty to take care of ill parent'},
{'D027': 'Important for succesful marriage: Faithfulness'},
{'D028': 'Important for succesful marriage: Adequate income'},
{'D029': 'Important for succesful marriage: Same social background'},
{'D030': 'Important for succesful marriage: Respect and appreciation'},
{'D031': 'Important for succesful marriage: Religious beliefs'},
{'D032': 'Important for succesful marriage: Good housing'},
{'D033': 'Important for succesful marriage: Agreement on politics'},
{'D034': 'Important in succesful marriage: Understanding and tolerance'},
{'D035': 'Important for succesful marriage: Apart from in-laws'},
{'D036': 'Important for succesful marriage: Happy sexual relationship'},
{'D037': 'Important for succesful marriage: Sharing household chores'},
{'D038': 'Important for succesful marriage: Children'},
{'D043': 'Important for succesful marriage: Tastes and interests in common'},
{'D054': 'One of main goals in life has been to make my parents proud'},
{'D055': 'Make effort to live up to what my friends expect'},
{'D056': 'Relationship working mother'},
{'D057': 'Being a housewife just as fulfilling'},
{'D058': 'Husband and wife should both contribute to income'},
{'D059': 'Men make better political leaders than women do'},
{'D060': 'University is more important for a boy than for a girl'},
{'D061': 'Pre-school child suffers with working mother'},
{'D062': 'Women want a home and children'},
{'D063': 'Job best way for women to be independent'},
{'D063_B': 'Job best way for women to be independent (b)'},
{'D066': 'Problem if women have more income than husband (4 categories)'},
{'D066_01': 'Problem if women have more income than husband (5 categories)'},
{'D066_B': 'Problem if women have more income than husband (3 categories)'},
{'D067': 'Traits in a woman: Woman wearing weil'},
{'D068': 'Traits in a woman: Woman good mother'},
{'D069': 'Traits in a woman: Woman good wife'},
{'D070': 'Traits in a woman: Woman religious'},
{'D071': 'Traits in a woman: Woman educated'},
{'D072': 'Traits in a woman: Woman being independent'},
{'D073': 'Traits in a woman: Woman having work outside home'},
{'D074': 'Traits in a woman: Woman maintaining her family'},
{'D075': 'Traits in a woman: Woman being sociable'},
{'D076': 'More than one wife'},
{'D077': 'Wife must obey'},
{'D078': 'Men make better business executives than women do'},
{'D079': 'I seek to be myself rather than to follow others'},
{'D080': 'I decide my goals in life by myself'},
{'D081': 'Homosexual couples are as good parents as other couples'},
{'E001': 'Aims of country: first choice'},
{'E002': 'Aims of country: second choice'},
{'E003': 'Aims of respondent: first choice'},
{'E004': 'Aims of respondent: second choice'},
{'E005': 'Most important: first choice'},
{'E006': 'Most important: second choice'},
{'E007': 'National goals: Maintaining order in the nation'},
{'E008': 'National goals: Giving people more say'},
{'E009': 'National goals: Fighting rising prices'},
{'E010': 'National goals: free speech'},
{'E012': 'Willingness to fight for country'},
{'E014': 'Future changes: Less emphasis on money and material possessions'},
{'E015': 'Future changes: Less importance placed on work'},
{'E016': 'Future changes: More emphasis on technology'},
{'E017': 'Future changes: More emphasis on individual'},
{'E018': 'Future changes: Greater respect for authority'},
{'E019': 'Future changes: More emphasis on family life'},
{'E020': 'Future changes: A simple and more natural lifestyle'},
{'E022': 'Opinion about scientific advances'},
{'E023': 'Interest in politics'},
{'E025': 'Political action: Signing a petition'},
{'E025B': 'Political action recently done: signing a petition'},
{'E026': 'Political action: joining in boycotts'},
{'E026B': 'Political action recently done: joining in boycotts'},
{'E027': 'Political action: attending lawful/peaceful demonstrations'},
{'E028': 'Political action: joining unofficial strikes'},
{'E028B': 'Political acition recently done: Joining strikes'},
{'E029': 'Political action: occupying buildings or factories'},
{'E032': 'Freedom or equality'},
{'E033': 'Self positioning in political scale'},
{'E034': 'Basic kinds of attitudes concerning society'},
{'E035': 'Income equality'},
{'E036': 'Private vs state ownership of business'},
{'E037': 'Government responsibility'},
{'E038': 'Job taking of the unemployed'},
{'E039': 'Competition good or harmful'},
{'E040': 'Hard work brings success'},
{'E041': 'Wealth accumulation'},
{'E045': 'Major changes in life'},
{'E046': 'New and old ideas'},
{'E047': 'Personal characteristics: Changes, worry or welcome possibility'},
{'E048': 'Personal characteristics: I usually count on being successful in everything I do'},
{'E049': 'Personal characteristics: I enjoy convincing others of my opinion'},
{'E050': 'Personal characteristics: I serve as a model for others'},
{'E051': 'Personal characteristics: I am good at getting what I want'},
{'E052': 'Personal characteristics: I own many things others envy me for'},
{'E053': 'Personal characteristics: I like to assume responsibility'},
{'E054': 'Personal characteristics: I am rarely unsure about how I should behave'},
{'E055': 'Personal characteristics: I often give others advice'},
{'E056': 'Personal characteristics: None of the above'},
{'E057': 'The economic system needs fundamental changes'},
{'E058': 'Our government should be made much more open to the public'},
{'E059': 'Allow more freedom for individuals'},
{'E060': 'I could do nothing about an unjust law'},
{'E061': 'Political reform is moving too rapidly'},
{'E062': 'Importation of goods'},
{'E063': 'Current society: Egalitarian vs. competitive society'},
{'E064': 'Current society: Extensive welfare vs. low taxes'},
{'E065': 'Current society: Regulated vs. responsible society'},
{'E066': 'Society aimed:  egalitarian vs. competitive'},
{'E067': 'Society aimed: extensive welfare vs. low taxes'},
{'E068': 'Society aimed: regulated vs. responsible society'},
{'E069_01': 'Confidence: Churches'},
{'E069_02': 'Confidence: Armed Forces'},
{'E069_03': 'Confidence: Education System'},
{'E069_04': 'Confidence: The Press'},
{'E069_05': 'Confidence: Labour Unions'},
{'E069_06': 'Confidence: The Police'},
{'E069_07': 'Confidence: Parliament'},
{'E069_08': 'Confidence: The Civil Services'},
{'E069_09': 'Confidence: Social Security System'},
{'E069_10': 'Confidence: Television'},
{'E069_11': 'Confidence: The Government'},
{'E069_12': 'Confidence: The Political Parties'},
{'E069_13': 'Confidence: Major Companies'},
{'E069_14': 'Confidence: The Environmental Protection Movement'},
{'E069_15': 'Confidence: The Women�s Movement'},
{'E069_17': 'Confidence: Justice System/Courts'},
{'E069_18': 'Confidence: The European Union'},
{'E069_18A': 'Confidence: Major regional organization (combined from country-specific)'},
{'E069_19': 'Confidence: NATO'},
{'E069_20': 'Confidence: The United Nations'},
{'E069_21': 'Confidence: The Arab League'},
{'E069_22': 'Confidence: The Association of South East Asian Nations -ASEAN'},
{'E069_23': 'Confidence: The Organization for African Unity-OAU'},
{'E069_24': 'Confidence: The NAFTA'},
{'E069_25': 'Confidence: The Andean pact'},
{'E069_26': 'Confidence: The Mercosur'},
{'E069_27': 'Confidence: The SAARC'},
{'E069_28': 'Confidence: The ECO'},
{'E069_29': 'Confidence: The APEC'},
{'E069_30': 'Confidence: The Free Commerce Treaty (Tratado de libre comercio)'},
{'E069_31': 'Confidence: The United American States Organization (Organizaci�n de Estados Unidos Americanos - OEA)'},
{'E069_32': 'Confidence: The �Movimiento en pro de Vieques�(Puerto Rico)'},
{'E069_33': 'Confidence: Local/Regional Government'},
{'E069_34': 'Confidence: SADC/SADEC'},
{'E069_35': 'Confidence: East African Cooperation (EAC)'},
{'E069_38': 'Confidence: The Presidency'},
{'E069_39': 'Confidence: The Civil Society Groups'},
{'E069_40': 'Confidence: Charitable or humanitarian organizations'},
{'E069_41': 'Confidence: Banks'},
{'E069_42': 'Confidence: CARICOM'},
{'E069_43': 'Confidence: CIS'},
{'E069_44': 'Confidence: Confidence in CER with Australia'},
{'E069_45': 'Confidence: International Monetary Found (IMF)'},
{'E069_46': 'Confidence: Non governmental Organizations (NGOs)'},
{'E069_47': 'Confidence: The American Forces'},
{'E069_48': 'Confidence: The non-Iraqi television'},
{'E069_49': 'Confidence: TV News'},
{'E069_51': 'Confidence: Religious leaders'},
{'E069_52': 'Confidence: Evangelic Church'},
{'E069_54': 'Confidence: Universities'},
{'E069_55': 'Confidence: The Organization of the Islamic World'},
{'E069_56': 'Confidence: The Organization of American States (OAE)'},
{'E069_57': 'Confidence: UNASUR'},
{'E069_58': 'Confidence: The Arab Maghreb Union'},
{'E069_59': 'Confidence: Cooperation Council for the Arab states of Gulf (GCC)'},
{'E069_60': 'Confidence: Mainland government'},
{'E069_61': 'Confidence: The World Trade Organization (WTO)'},
{'E069_62': 'Confidence: The World Health Organization (WHO)'},
{'E069_63': 'Confidence: The World Bank'},
{'E069_64': 'Confidence: Elections'},
{'E069_65': 'Confidence: International Criminal Court (ICC)'},
{'E069_66': 'Confidence: UNDP United Nations Development Programme'},
{'E069_67': 'Confidence: The African Union (AU)'},
{'E104': 'Approval: Ecology movement or nature protection'},
{'E105': 'Approval: Anti-nuclear energy movement'},
{'E106': 'Approval: Disarmament movement'},
{'E107': 'Approval: Human rights movement'},
{'E108': 'Approval: Women�s movement'},
{'E109': 'Approval: Anti-apartheid movement'},
{'E110': 'Satisfaction with the way democracy develops'},
{'E111': 'Rate political system for governing country'},
{'E111_01': 'Satisfaction with the political system performance'},
{'E112': 'Rate political system as it was before'},
{'E113': 'Rate political system in ten years'},
{'E114': 'Political system: Having a strong leader'},
{'E115': 'Political system: Having experts make decisions'},
{'E116': 'Political system: Having the army rule'},
{'E117': 'Political system: Having a democratic political system'},
{'E117B': 'Political system: Having a system governed by religious law in which there are no political parties or elections'},
{'E118': 'Firm party leader vs. Cooperating party leader'},
{'E119': 'Government order vs. freedom'},
{'E120': 'In democracy, the economic system runs badly'},
{'E121': 'Democracies are indecisive and have too much squabbling'},
{'E122': 'Democracies aren�t good at maintaining order'},
{'E123': 'Democracy may have problems but is better'},
{'E124': 'Respect for individual human rights nowadays'},
{'E125': 'Satisfaction with the people in national office'},
{'E127': 'Free market economy right for country future'},
{'E128': 'Country is run by big interest vs. for all people�s benefit'},
{'E129': 'Economic aid to poorer countries'},
{'E129A': 'Amount of foreign aid of this country'},
{'E129B': 'How much more foreign aid this country should contribute'},
{'E129C': 'Be willing to pay higher taxes in order to increase country�s foreign aid'},
{'E129D': 'Economic aid to poorer countries (favor/against)'},
{'E130': 'Poverty compared to 10 years ago'},
{'E131': 'Why are people in need'},
{'E132': 'Chance to escape from poverty'},
{'E133': 'How much is the government doing against poverty'},
{'E134': 'Amount of help for less developed countries'},
{'E135': 'Who should decide: international peacekeeping'},
{'E136': 'Who should decide: protection of the environment'},
{'E137': 'Who should decide: aid to developing countries'},
{'E138': 'Who should decide: refugees'},
{'E139': 'Who should decide: human rights'},
{'E140': 'Country cannot solve environmental problems by itself'},
{'E141': 'Country cannot solve crime problems by itself'},
{'E142': 'Country cannot solve employment problems by itself'},
{'E143': 'Immigrant policy'},
{'E150': 'How often follows politics in the news'},
{'E179_WVS7LOC': 'Which party would you vote for if there were a national election tomorrow (Local names)'},
{'E179WVS': 'Which party would you vote for: first choice (WVS)'},
{'E180WVS': 'Which party would you vote for: second choice (WVS)'},
{'E182': 'Party that would never vote'},
{'E184': 'Aggression from neighbouring country'},
{'E185': 'Exploitation of local resources'},
{'E186': 'Cultural invasion by the west'},
{'E188': 'Frequency watches TV'},
{'E189': 'TV most important entertainment'},
{'E190': 'Why are there people living in need: first'},
{'E191': 'Why are there people living in need: second'},
{'E192': 'Least liked group in society'},
{'E193': 'Least liked allow: hold office'},
{'E194': 'Least liked allow: teach'},
{'E195': 'Least liked allow: demonstrate'},
{'E196': 'Extent of political corruption'},
{'E198': 'Using violence for political goals not justified'},
{'E203': 'Rapid implementation of market reforms have negative impact on national stability'},
{'E204': 'Effect of market economic reforms'},
{'E205': 'Political parties serve the social and political needs of people'},
{'E206': 'Free and fair elections will reduce terrorism'},
{'E207': '[Country] should have close relations with France'},
{'E208': '[Country] should have close relations with United States'},
{'E209': 'Would persist to immigrate abroad if R�s economic situation was better'},
{'E211': 'Opinion about the problem of Palestine and Israel'},
{'E212': 'Opinion about 11th september airliners crash action by religious fundamentalists'},
{'E213': 'Woman should not work outside unless forced to do so'},
{'E214': 'Western democracy is the best political system for country'},
{'E215': 'It is necessary to fight terrorism by military means'},
{'E216': '[Country] needs foreign military cooperation to combat terrorism'},
{'E217': 'Science and technology are making our lives healthier, easier, and more comfortable'},
{'E218': 'Because of science and technology, there will be more opportunities for the next generation'},
{'E219': 'Science and technology make our way of life change too fast'},
{'E220': 'We depend too much on science and not enough on faith'},
{'E221B': 'Political action recently done: Attending peaceful/lawful demonstrations'},
{'E222': 'Political action: Other'},
{'E222B': 'Political action recently done: Other'},
{'E224': 'Democracy: Governments tax the rich and subsidize the poor.'},
{'E225': 'Democracy: Religious authorities interpret the laws.'},
{'E226': 'Democracy: People choose their leaders in free elections.'},
{'E227': 'Democracy: People receive state aid for unemployment.'},
{'E228': 'Democracy: The army takes over when government is incompetent.'},
{'E229': 'Democracy: Civil rights protect people�s liberty against oppression.'},
{'E230': 'Democracy: The economy is prospering.'},
{'E231': 'Democracy: Criminals are severely punished.'},
{'E232': 'Democracy: People can change the laws in referendums.'},
{'E233': 'Democracy: Women have the same rights as men.'},
{'E233A': "Democracy: The state makes people's incomes equal"},
{'E233B': 'Democracy: People obey their rulers'},
{'E234': 'The world is better off, or worse off, because of science and technology'},
{'E235': 'Importance of democracy'},
{'E236': 'Democraticness in own country'},
{'E237': 'Heard of the Millennium Development Goals'},
{'E238': 'Most serious problem of the world: 1st choice'},
{'E239': 'Most serious problem of the world: 2nd choice'},
{'E240': 'Most serious problem for own country: 1st choice'},
{'E241': 'Most serious problem for own country: 2nd choice'},
{'E242': 'MDG: Reduce extreme poverty'},
{'E243': 'MDG: Increase primary education'},
{'E244': 'MDG: Reduce child mortality'},
{'E245': 'MDG: Fight HIV'},
{'E246': 'MDG: Improve housing conditions'},
{'E247': 'Priority: Global poverty versus National problems'},
{'E248': 'Information source: Daily newspaper'},
{'E248B': 'Information source: Daily newspaper (B)'},
{'E249': 'Information source: News broadcasts on radio or TV'},
{'E250': 'Information source: Printed magazines'},
{'E250B': 'Information source: Printed magazines (B)'},
{'E251': 'Information source: In depth reports on radio or TV'},
{'E252': 'Information source: Books'},
{'E253': 'Information source: Internet, Email'},
{'E253B': 'Information source: Social media (Facebook, Twitter, etc.)'},
{'E254': 'Information source: Talk with friends or colleagues'},
{'E254B': 'Information source: Talk with friends or colleagues (B)'},
{'E255': 'How often use of PC'},
{'E256': 'General party preference'},
{'E257': 'Voted in recent parliament elections'},
{'E258': 'Information source: TV news'},
{'E258B': 'Information source: TV news (B)'},
{'E259': 'Information source: Radio news'},
{'E259B': 'Information source: Radio news (B)'},
{'E260': 'Information source: Mobile phone'},
{'E260B': 'Information source: Mobile phone (B)'},
{'E261': 'Information source: Email'},
{'E261B': 'Information source: Email (B)'},
{'E262': 'Information source: Internet'},
{'E262B': 'Information source: Internet (B)'},
{'E263': 'Vote in elections: local level'},
{'E264': 'Vote in elections: National level'},
{'E265_01': "How often in country's elections: Votes are counted fairly"},
{'E265_02': "How often in country's elections: Opposition candidates are prevented from running"},
{'E265_03': "How often in country's elections: TV news favors the governing party"},
{'E265_04': "How often in country's elections: Voters are bribed"},
{'E265_05': "How often in country's elections: Journalists provide fair coverage of elections"},
{'E265_06': "How often in country's elections: Election officials are fair"},
{'E265_07': "How often in country's elections: Rich people buy elections"},
{'E265_08': "How often in country's elections: Voters are threatened with  violence at the polls"},
{'E265_09': "How often in country's elections: Voters are offered a genuine choice in the elections"},
{'E265_10': 'How often in country�s elections: Women have equal opportunities to run the office'},
{'E266': 'Some people think that having honest elections makes a lot of difference in their lives;  other people think that it doesn�t matter much'},
{'E267': 'Importance of having honest elections in whether or not this country develops economically'},
{'E268': 'Scale corruption in [my country] - pay a bribe, give a gift, do a favor to other to get things'},
{'E269': 'Groups of people involved in corruption: State authorities'},
{'E270': 'Groups of people involved in corruption: Business executives'},
{'E271': 'Groups of people involved in corruption: Local authorities'},
{'E272': 'Groups of people involved in corruption: Civil service providers (police, judiciary, civil servants, doctors, teachers)'},
{'E273': 'Groups of people involved in corruption: Journalists and media'},
{'E274': 'Frequency ordinary people pay a bribe, give a gift or do a favor to local officials/service providers in order to get services'},
{'E275': 'Degree of agreement: On the whole, women are less corrupt than men'},
{'E276': 'Risk in this country to be held accountable for giving or receiving a bribe, gift or favor in return for public service'},
{'E277': 'Standard of living comparing with your parents'},
{'E278': 'Should international organizations prioritize, being effective or being democratic'},
{'E279': 'Five countries have permanent seats on the Security Council of the United Nations. Which ones of the following is not a member?'},
{'E280': 'Where are the headquarters of the International Monetary Fund (IMF) located?'},
{'E281': 'Which of the following problems does the organization Amnesty International deal with?'},
{'E282': 'Political actions using Internet: Searching information about politics and political events'},
{'E283': 'Political actions using Internet: Signing an electronic petition'},
{'E284': 'Political actions using Internet: Encouraging other people to take any form of political action'},
{'E285': 'Political actions using Internet: Organizing political activities, events, protests'},
{'E286': 'Social activism: Donating to a group or campaign'},
{'E287': 'Social activism: Contacting a government official'},
{'E288': 'Social activism: Encouraging others to take action about political issues'},
{'E289': 'Social activism: Encouraging others to vote'},
{'E290': 'Justifiable: Political violence'},
{'E291': 'How much would you say the political system in your country allows people like you to have a say in what the government does?'},
{'F001': 'Thinking about meaning and purpose of life'},
{'F003': 'Thinking about death'},
{'F004': 'Life is meaningful because God exits'},
{'F005': 'Try to get the best out of life'},
{'F006': 'Death is inevitable'},
{'F007': 'Death has meaning if you believe in God'},
{'F008': 'Death is a natural resting point'},
{'F009': 'Sorrow has meaning if you believe in God'},
{'F010': 'Life has no meaning'},
{'F022': 'Statement: good and evil'},
{'F025': 'Religious denominations - major groups'},
{'F025_WVS': 'Religious denomination - detailed list'},
{'F025old': 'Religious denomination'},
{'F027': 'Which former religious denomination'},
{'F028': 'How often do you attend religious services'},
{'F028B': 'How often to you pray'},
{'F029': 'Raised religiously'},
{'F031': 'Important: Religious service birth'},
{'F032': 'Important: Religious service marriage'},
{'F033': 'Important: Religious service death'},
{'F034': 'Religious person'},
{'F035': 'Churches give answers: moral problems'},
{'F036': 'Churches give answers: the problems of family life'},
{'F037': 'Churches give answers: people�s spiritual needs'},
{'F038': 'Churches give answers: the social problems'},
{'F040': 'Churches speak out on: disarmament'},
{'F041': 'Churches speak out on: abortion'},
{'F042': 'Churches speak out on: third world problems'},
{'F043': 'Churches speak out on: extramarital affairs'},
{'F044': 'Churches speak out on: unemployment'},
{'F045': 'Churches speak out on: racial discrimination'},
{'F046': 'Churches speak out on: euthanasia'},
{'F047': 'Churches speak out on: homosexuality'},
{'F048': 'Churches speak out on: ecology and environmental issues'},
{'F049': 'Churches speak out on: government policy'},
{'F050': 'Believe in: God'},
{'F051': 'Believe in: life after death'},
{'F052': 'Believe in: people have a soul'},
{'F053': 'Believe in: hell'},
{'F054': 'Believe in: heaven'},
{'F055': 'Believe in: Sin'},
{'F057': 'Believe in: re-incarnation'},
{'F059': 'Believe in: devil'},
{'F060': 'Believe in: resurrection of the dead'},
{'F062': 'Personal God vs. Spirit or Life Force'},
{'F063': 'How important is God in your life'},
{'F064': 'Get comfort and strength from religion'},
{'F065': 'Moments of prayer, meditation...'},
{'F066': 'Pray to God outside of religious services (I)'},
{'F067': 'Pray to God outside of religious services (ii)'},
{'F102': 'Politicians who don�t believe in God are unfit for public office'},
{'F103': 'Religious leaders should not influence how people vote'},
{'F104': 'Better if more people with strong religious beliefs in public office'},
{'F105': 'Religious leaders should not influence government'},
{'F108': 'Government protects freedom'},
{'F109': 'Government protects religion'},
{'F110': 'Laws: people�s wishes'},
{'F111': 'Only laws of the Shari�a'},
{'F114A': 'Justifiable: Claiming government benefits to which you are not entitled'},
{'F114B': 'Justifiable: Stealing property'},
{'F114C': 'Justifiable: Parents beating children'},
{'F114D': 'Justifiable: Violence against other people'},
{'F114E': 'Justifiable: Terrorism as a political, ideological or religious mean'},
{'F115': 'Justifiable: Avoiding a fare on public transport'},
{'F116': 'Justifiable: Cheating on taxes'},
{'F117': 'Justifiable: Someone accepting a bribe'},
{'F118': 'Justifiable: Homosexuality'},
{'F119': 'Justifiable: Prostitution'},
{'F120': 'Justifiable: Abortion'},
{'F121': 'Justifiable: Divorce'},
{'F122': 'Justifiable: Euthanasia'},
{'F123': 'Justifiable: Suicide'},
{'F124': 'Justifiable: Drinking alcohol'},
{'F125': 'Justifiable: Joyriding'},
{'F126': 'Justifiable: Taking soft drugs'},
{'F127': 'Justifiable: Llying'},
{'F128': 'Justifiable: Adultery'},
{'F129': 'Justifiable: Throwing away litter'},
{'F130': 'Justifiable: Driving under influence of alcohol'},
{'F132': 'Justifiable: Having casual sex'},
{'F135': 'Justifiable: Sex under the legal age of consent'},
{'F135A': 'Justifiable: Sex before marriage'},
{'F136': 'Justifiable: Political assassination'},
{'F139': 'Justifiable: Buy stolen goods'},
{'F140': 'Justifiable: Keeping money that you have found'},
{'F141': 'Justifiable: Fighting with the police'},
{'F142': 'Justifiable: Failing to report damage you�ve done accidentally to a parked vehicle'},
{'F143': 'Justifiable: Threatening workers who refuse to join a strike'},
{'F144': 'Justifiable: Klling in self-defence'},
{'F144_02': 'Justifiable: Death penalty'},
{'F164': 'Islam requires woman to dress modestly but does not require cover face with veil'},
{'F165': 'Violation of Islam for male and female university students to attend classes together'},
{'F166': 'By requiring man treat all wives equally, Islam true intent is prohibit taking more than one wife'},
{'F167': 'Monarchy is a form of government that is compatible with Islam'},
{'F168': 'Democracy is a Western form of government that is not compatible with Islam'},
{'F169': 'Nationalism is incompatible with Islam because Islam requires �ummah�'},
{'F170': 'If Palestinian state established and peace with Israel, Islam would not oppose existence of Israel'},
{'F171': 'If country pursues policies harmful to Muslims, Islam permits killing civilians in that country'},
{'F172': 'A truly Islamic country should not have a parliament with the right to pass laws'},
{'F173': 'Islam requires that political rights of non Muslims should be inferior to those of Muslims'},
{'F174': 'Islams requires country with majority of Muslims be governed by men of Islamic learning'},
{'F175': 'Religions limit democratic processes'},
{'F176': 'Some US Policies toward other countries are good and some are bad'},
{'F177': 'While US policies toward other countries are often bad, most ordinary americans are good people'},
{'F178': 'The culture of US and other Western countries has many positive attributes'},
{'F179': 'Exposure to the culture of the US and other Western countries harmful effect on our country'},
{'F186': 'Religion is a cause of terrorism'},
{'F187': 'The content of [Country] education contributes to religious extremism'},
{'F188': 'Which is more important as a basis for marriage:  parents� approval or love'},
{'F189': 'When you were growing up, did your father or mother have more influence in the affairs of the house'},
{'F190': 'How frequently do you perform the five prescribed prayers of the Islam'},
{'F191': 'How frequently do you perform in the mosque'},
{'F192': 'If you feel sad and want to talk to someone, to whom do you usually turn to'},
{'F193': 'Civil marriage is very important because it helps maintain the family'},
{'F194': 'How important: daily prayer'},
{'F195': 'How important: building a prosperous society'},
{'F196': 'How important: forming a happy secure family'},
{'F197': 'How important: building a successful professional future'},
{'F198': 'Fate versus control'},
{'F199': 'Justifiable: For a man to beat his wife'},
{'F200': 'Meaning of religion: To follow religious norms and ceremonies vs To do good to other people'},
{'F201': 'Meaning of religion: To make sense of life after death vs To make sense of life in this world'},
{'F202': 'Whenever science and religion conflict,  religion is always right'},
{'F203': 'The only acceptable religion  is my religion'},
{'F204': 'All religions should be taught in public schools'},
{'F205': 'People who belong to different religions are probably just as moral as those who belong to mine'},
{'F206': 'Degree of agreement: Nowadays one often has trouble deciding which moral rules are the right ones to follow'},
{'G001': 'Geographical groups belonging to first'},
{'G001CS': 'Geographical groups belonging to first (country specific)'},
{'G002': 'Geographical groups belonging to second'},
{'G002CS': 'Geographical groups belonging to second  (country specific)'},
{'G003CS': 'Geographical groups belonging to least of all (country specific)'},
{'G005': 'Citizen of [country]'},
{'G006': 'How proud of nationality'},
{'G007_01': 'Trust: Other people in country'},
{'G007_02': 'Trust: French Canadians'},
{'G007_03': 'Trust: Nepalis'},
{'G007_04': 'Trust: Korean residents in Japan'},
{'G007_05': 'Trust: Chinese residents in Japan'},
{'G007_06': 'Trust: Mestizo'},
{'G007_07': 'Trust: Indians'},
{'G007_08': 'Trust: Central Americans'},
{'G007_09': 'Trust: Hausas'},
{'G007_10': 'Trust: Igbos'},
{'G007_11': 'Trust: Yorubas'},
{'G007_12': 'Trust: Ghanaians'},
{'G007_13': 'Trust: Czechs'},
{'G007_16': 'Trust: West Germans'},
{'G007_17': 'Trust: Your friends'},
{'G007_18': 'Trust: Your neighborhood'},
{'G007_18_B': 'Trust: Your neighborhood (B)'},
{'G007_19': 'Trust: White South Africans'},
{'G007_20': 'Trust: Black South Africans'},
{'G007_21': 'Trust: Coloured South Africans'},
{'G007_22': 'Trust: Asian South Africans'},
{'G007_28': 'Trust: Moroccans'},
{'G007_30': 'Trust: Portuguese'},
{'G007_31': 'Trust: Koreans'},
{'G007_32': 'Trust: Soviet Union people'},
{'G007_33_B': 'Trust: People you know personally (B)'},
{'G007_34_B': 'Trust: People you meet for the first time (B)'},
{'G007_35_B': 'Trust: People of another religion (B)'},
{'G007_36_B': 'Trust: People of another nationality (B)'},
{'G007_37': 'Trust: Americans'},
{'G007_39': 'Trust: Russians'},
{'G007_40': 'Trust: Chinese'},
{'G007_41': 'Trust: Italians'},
{'G007_42': 'Trust: Latin Americans'},
{'G007_43': 'Trust: Japanese'},
{'G007_44': 'Trust: Blacks'},
{'G007_45': 'Trust: Germans'},
{'G007_48': 'Trust: Mapuche Indians'},
{'G007_49': 'Trust: Pascuences'},
{'G007_50': 'Confianza: Argentinos'},
{'G007_51': 'Trust: Peruvians'},
{'G007_52': 'Trust: Chinese Zhuan Nationality'},
{'G007_53': 'Trust: Chinese Hui Nationality'},
{'G007_54': 'Trust: English'},
{'G007_55': 'Trust: Slovaks'},
{'G007_56': 'Trust: Gypsies'},
{'G007_57': 'Trust: Poles'},
{'G007_58': 'Trust: Indian Hindus'},
{'G007_59': 'Trust: Indian Non-Hindus'},
{'G007_60': 'Trust: Pakistanis'},
{'G007_61': 'Trust: Canadian people in general'},
{'G007_62': 'Trust: Christians'},
{'G007_63': 'Trust: Kurds'},
{'G007_64': 'Trust: People in general'},
{'G007_65': 'Trust: Relatives'},
{'G007_66': 'Trust: Shi�i'},
{'G007_67': 'Trust: Sunni'},
{'G015': 'Which of the following best describes you'},
{'G015B': 'Which of the following best describes you (B)'},
{'G016': 'Language at home'},
{'G017': 'Born in this country: birth country'},
{'G018': 'When came to country'},
{'G019': 'I see myself as a world citizen'},
{'G020': 'I see myself as member of my local community'},
{'G021': 'I see myself as citizen of the [country] nation'},
{'G022A': 'I see myself as citizen of [Latinamerica]'},
{'G022B': 'I see myself as citizen of [North America]'},
{'G022C': 'I see myself as citizen of the [European Union]'},
{'G022D': 'I see myself as citizen of [APEC]'},
{'G022E': 'I see myself as citizen of [ASIA]'},
{'G022F': 'I see myself as citizen of [Mercosur]'},
{'G022G': 'I see myself as citizen of [my province or region]'},
{'G022H': 'I see myself as citizen of [a country other than mine]'},
{'G022I': 'I see myself as citizen of [CIS]'},
{'G022J': 'I see myself as citizen of [The Caribbean]'},
{'G022K': 'I see myself as citizen of [The African Union]'},
{'G022L': 'I see myself as citizen of [Arab Maghreb Union]'},
{'G022M': 'I see myself as citizen of [ASEAN]'},
{'G022N': 'I see myself as citizen of [Arab Union]'},
{'G022O': 'I see myself as citizen of the [Northeast Asia Region]'},
{'G022P': 'I see myself as citizen of the [UNASUR]'},
{'G022Q': 'I see myself as citizen of the [Islamic nation]'},
{'G022R': 'I see myself as part of the Cooperation Council for the Arab states of Gulf (GCC)'},
{'G022S': 'I see myself as part of  [SAARC]'},
{'G023': 'I see myself as an autonomous individual'},
{'G024': 'What thing are you proud of in your country -1st'},
{'G025': 'What thing are you proud of in your country -2nd'},
{'G026': 'Mother immigrant'},
{'G026_01': "Mother's Country of origin"},
{'G027': 'Father immigrant'},
{'G027_01': "Father's Country of origin"},
{'G027A': 'Respondent immigrant'},
{'G027B': 'Respondent citizen'},
{'G028': 'Requirements for citizenship: having ancestors from my country'},
{'G029': 'Requirements for citizenship: being born on my country�s soil'},
{'G030': 'Requirements for citizenship: adopting the customs of my country'},
{'G031': 'Requirements for citizenship: abiding by my country�s laws'},
{'G032': 'Ethnic diversity'},
{'G052': 'Evaluate the impact of immigrants on the development of [your country]'},
{'G053': 'Effects of immigrants on the development of [your country]: Fill useful jobs in the workforce'},
{'G054': 'Effects of immigrants on the development of [your country]: Strengthen cultural diversity'},
{'G055': 'Effects of immigrants on the development of [your country]: Increase the crime rate'},
{'G056': 'Effects of immigrants on the development of [your country]: Give asylum to political refugees'},
{'G057': 'Effects of immigrants on the development of [your country]: Increase the risks of terrorism'},
{'G058': 'Effects of immigrants on the development of [your country]: Help poor people establish new lives'},
{'G059': 'Effects of immigrants on the development of [your country]: Increase unemployment'},
{'G060': 'Effects of immigrants on the development of [your country]: Lead to social conflict'},
{'G062': 'How close you feel: Continent; e.g. Europe, Asia etc.]'},
{'G063': 'How close you feel: World'},
{'G255': 'How close you feel: Your [village, town or city]'},
{'G256': 'Feel close to your district, region'},
{'G257': 'Feel close to your country'},
{'H001': 'Secure in neighborhood'},
{'H002_01': 'Frequency in your neighborhood: Robberies'},
{'H002_02': 'Frequency in your neighborhood: Alcohol consumed in the streets'},
{'H002_03': 'Frequency in your neighborhood: Police or military interfere with people�s private life'},
{'H002_04': 'Frequency in your neighborhood: Racist behavior'},
{'H002_05': 'Frequency in your neighborhood: Drug sale in streets'},
{'H003_01': 'Things done for reasons of security: Didn�t carry much money'},
{'H003_02': 'Things done for reasons of security: Preferred not to go out at night'},
{'H003_03': 'Things done for reasons of security: Carried a knife, gun or other weapon'},
{'H004': 'Respondent was victim of a crime during the past year'},
{'H005': "Respondent's family was victim of a crime during last year"},
{'H006_01': 'Worries: Losing my job or not finding a job'},
{'H006_02': "Worries: Not being able to give one's children a good education"},
{'H006_03': 'Worries: A war involving my country'},
{'H006_04': 'Worries: A terrorist attack'},
{'H006_05': 'Worries: A civil war'},
{'H006_06': 'Worries: Government wire-tapping or reading my mail or email'},
{'H007': 'Under some conditions, war is necessary to obtain justice'},
{'H008_01': 'Frequency you/family (last 12 month): Gone without enough food to eat'},
{'H008_02': 'Frequency you/family (last 12 month): Felt unsafe from crime in your own home'},
{'H008_03': 'Frequency you/family (last 12 month): Gone without needed medicine or treatment that you needed'},
{'H008_04': 'Frequency you/family (last 12 month): Gone without a cash income'},
{'H008_05': 'How frequently do the following things occur in your neighborhood: Street violence and fights'},
{'H008_06': 'How frequently do the following things occur in your neighborhood: Sexual harassment'},
{'H008_07': 'Freedom and Equality - Which more important'},
{'H008_08': 'Freedom and securiy - Which more important'},
{'H008_09': 'In the last 12 month, how often have you or your family: Gone without a safe shelter over your head'},
{'H009': 'Government has the right: Keep people under video surveillance in public areas'},
{'H010': 'Government has the right: Monitor all e-mails and any other information exchanged on the Internet'},
{'H011': 'Government has the right: Collect information about anyone living in [COUNTRY] without their knowledge'},
{'I001': 'One of the bad effects of science is that it breaks down people�s ideas of right and wrong'},
{'I002': 'It is not important for me to know about science in my daily life'},
{'MODE': 'Mode of data collection'},
{'PWGHT': 'Population size weight'},
{'S002VS': 'Chronology of EVS-WVS waves'},
{'S003': 'ISO 3166-1 numeric country code'},
{'S006': 'Original respondent number'},
{'S007': 'Unified respondent number'},
{'S008': 'Interviewer number'},
{'S010': 'Total length of interview'},
{'S011A': 'Time of the interview - Start'},
{'S011B': 'Time at the end of interview'},
{'S012': 'Date interview'},
{'S013': 'Respondent interested during the interview'},
{'S013B': 'Interview privacy'},
{'S016': 'Language of the interview (WVS/EVS list of languages)'},
{'S016B': 'Language in which interview was conducted'},
{'S017': 'Weight'},
{'S018': 'Equilibrated weight-1000'},
{'S020': 'Year survey'},
{'S021': 'Country - wave - study - set - year'},
{'S022': 'Year/month of start-fieldwork'},
{'S023': 'Year/month of end-fieldwork'},
{'S024': 'Country - wave'},
{'S025': 'Country - year'},
{'V001': 'Father born in country'},
{'V001A': 'Fathers country of birth - ISO 3166-1 code'},
{'V002': 'Mother born in country'},
{'V002A': 'Mothers country of birth - ISO 3166-1 code'},
{'V004AF_01': 'Highest educational level attained - Respondent�s Father ISCED'},
{'V004AM_01': 'Highest educational level attained - Respondent�s Mother ISCED'},
{'V004RF': 'Highest educational level attained - Respondent�s Father (Recoded)'},
{'V004RM': 'Highest educational level attained - Respondent�s Mother (Recoded)'},
{'V097EF': 'Respondent�s Father - Occupational group (when respondent was 14 years old) (WVS)'},
{'W002A_01': 'Highest educational level attained - Respondent�s Spouse ISCED'},
{'W002D': 'Country specific: Education level partner'},
{'W002R': 'educational level partner (recoded)'},
{'W003': 'Employment status - Responent�s Spouse'},
{'W006E': 'Respondent�s Spouse - Occupational group (WVS)'},
{'X001': 'Sex'},
{'X002': 'Year of birth'},
{'X002_02A': 'Respondents country of birth - ISO 3166-1 code'},
{'X003': 'Age'},
{'X003R': 'Age recoded (6 intervals)'},
{'X003R2': 'Age recoded (3 intervals)'},
{'X007': 'Marital status'},
{'X008': 'Have you been married before'},
{'X010': 'Where r lived after married'},
{'X011': 'How many children do you have'},
{'X011A': 'Have you had any children'},
{'X012': 'How many are still living at home'},
{'X013': 'Number of people in household'},
{'X023': 'What age did you complete your education'},
{'X023R': 'What age did you complete your education (recoded in intervals)'},
{'X024B': 'Respondent - literate'},
{'X025': 'Highest educational level attained'},
{'X025A_01': 'Highest educational level attained - Respondent ISCED-2011'},
{'X025CSWVS': 'Education (country specific)'},
{'X025LIT': 'Was the respondent literate'},
{'X025R': 'Education level (recoded)'},
{'X026': 'Do you live with your parents'},
{'X028': 'Employment status'},
{'X031': 'Are you supervising someone'},
{'X036': 'Profession/job'},
{'X036E': 'Respondent - Occupational group (WVS)'},
{'X040': 'Are you the chief wage earner in your house'},
{'X041': 'Is the chief wage earner employed now'},
{'X043': 'Chief wage earner profession/job'},
{'X044': 'Family savings during past year'},
{'X045': 'Social class (subjective)'},
{'X045B': 'Social class (subjective) with 6 categories'},
{'X046': 'Socio-economic status of respondent'},
{'X047_WVS': 'Scale of incomes'},
{'X047CS': 'Scale of incomes (Country specific)'},
{'X047R_WVS': 'Subjective income level (recoded in 3 groups)'},
{'X048ISO': 'Region ISO 3166-2'},
{'X048WVS': 'Region where the interview was conducted (WVS)'},
{'X049': 'Settlement size'},
{'X049A': 'Settlement size_5 groups'},
{'X049CS': 'Settlement size (country specific)'},
{'X050': 'Type of habitat'},
{'X050B': 'Settlement type where interview was conducted'},
{'X050C': 'Urban/Rural habitat'},
{'X051': 'Ethnic group'},
{'X052': 'Institution of occupation'},
{'X053': 'Nature of tasks: manual vs. Cognitive'},
{'X054': 'Nature of tasks: routine vs. Creative'},
{'X055': 'Nature of tasks: independence'},
{'Y001': 'Post-Materialist index 12-item'},
{'Y002': 'Post-Materialist index 4-item'},
{'Y003': 'Autonomy Index'},
{'Y010': 'SACSECVAL.- Welzel Overall Secular Values'},
{'Y011': 'DEFIANCE.- Welzel defiance sub-index'},
{'Y011A': 'AUTHORITY - Welzel defiance - 1: Inverse respect for authority'},
{'Y011B': 'NATIONALISM - Welzel defiance - 2: Inverse national pride'},
{'Y011C': 'DEVOUT- Welzel defiance - 3: Inverse devoutness'},
{'Y012': 'DISBELIEF.- Welzel disbelief sub-index'},
{'Y012A': 'RELIGIMP - Welzel disbelief- 1: Inverse importance of religion'},
{'Y012B': 'RELIGBEL - Welzel disbelief- 2: Inverse religious person'},
{'Y012C': 'RELIGPRAC - Welzel disbelief- 3: Inverse religious practice'},
{'Y013': 'RELATIVISM.- Welzel relativism'},
{'Y013A': 'NORM1 - Welzel relativism- 1: Inverse norm conform1'},
{'Y013B': 'NORM2 - Welzel relativism- 2: Inverse norm conform2'},
{'Y013C': 'NORM3 - Welzel relativism- 3: Inverse norm conform3'},
{'Y014': 'SCEPTICISM.- Welzel scepticism index'},
{'Y014A': 'TRUSTARMY- Welzel scepticism- 1: Inverse trust in army'},
{'Y014B': 'TRUSTPOLICE- Welzel scepticism- 2: Inverse trust in police'},
{'Y014C': 'TRUSTCOURTS- Welzel scepticism- 3: Inverse trust in courts'},
{'Y020': 'RESEMAVAL.- Welzel emancipative values'},
{'Y021': 'AUTONOMY.- Wezel Autonomy subindex'},
{'Y021A': 'INDEP- Welzel autonomy-1: Independence as kid quality'},
{'Y021B': 'IMAGIN- Welzel autonomy-2: Imagination as kid quality'},
{'Y021C': 'NONOBED- Welzel autonomy-3: Obedience as kid quality'},
{'Y022': 'EQUALITY.- Welzel equality sub-index'},
{'Y022A': 'WOMJOB- Welzel equality-1: Gender equality: job'},
{'Y022B': 'WOMPOL- Welzel equality-2: Gender equality: politics'},
{'Y022C': 'WOMEDU- Welzel equality-3: Gender equality: education'},
{'Y023': 'CHOICE.- Welzel choice sub-index'},
{'Y023A': 'HOMOLIB- Welzel choice-1: Homosexuality acceptance'},
{'Y023B': 'ABORTLIB- Welzel choice-2: Abortion acceptable'},
{'Y023C': 'DIVORLIB- Welzel choice-3: Divorce acceptable'},
{'Y024': 'VOICE.- Welzel voice sub-index'},
{'Y024A': 'VOICE1- Welzel voice-1'},
{'Y024B': 'VOICE2- Welzel voice-2'},
{'Y024C': 'VOI2_00- Welzel voice-3 (auxiliary)'},
]