variable_mappings= [
    {'A001': 'Important in life: Family'},
{'A002': 'Important in life: Friends'},
{'A003': 'Important in life: Leisure time'},
{'A004': 'Important in life: Politics'},
{'A005': 'Important in life: Work'},
{'A006': 'Important in life: Religion'},
{'A008': 'Feeling of happiness'},
{'A009': 'State of health (subjective)'},
{'A025': 'Respect and love for parents'},
{'A026': 'Parents responsibilities to their children'},
{'A027': 'Important child qualities: Good manners'},
{'A029': 'Important child qualities: independence'},
{'A030': 'Important child qualities: Hard work'},
{'A032': 'Important child qualities: feeling of responsibility'},
{'A034': 'Important child qualities: imagination'},
{'A035': 'Important child qualities: tolerance and respect for other people'},
{'A038': 'Important child qualities: thrift saving money and things'},
{'A039': 'Important child qualities: determination perseverance'},
{'A040': 'Important child qualities: religious faith'},
{'A041': 'Important child qualities: unselfishness'},
{'A042': 'Important child qualities: obedience'},
{'A062': 'How often discusses political matters with friends'},
{'A064': 'Member: Belong to social welfare service for elderly'},
{'A065': 'Member: Belong to religious organization'},
{'A066': 'Member: Belong to education, arts, music or cultural activities'},
{'A067': 'Member: Belong to labour unions'},
{'A068': 'Member: Belong to political parties'},
{'A069': 'Member: Belong to local political actions'},
{'A070': 'Member: Belong to human rights'},
{'A071': 'Member: Belong to conservation, the environment, ecology, animal rights'},
{'A072': 'Member: Belong to professional associations'},
{'A073': 'Member: Belong to youth work'},
{'A074': 'Member: Belong to sports or recreation'},
{'A075': 'Member: Belong to women�s group'},
{'A076': 'Member: Belong to peace movement'},
{'A077': 'Member: Belong to organization concerned with health'},
{'A079': 'Member: Belong to other groups'},
{'A081': 'Voluntary work: Unpaid work social welfare service for elderly, handicapped or deprived people'},
{'A082': 'Voluntary work: Unpaid work religious or church organization'},
{'A083': 'Voluntary work: Unpaid work education, arts, music or cultural activities'},
{'A084': 'Voluntary work: Unpaid work labour unions'},
{'A085': 'Voluntary work: Unpaid work political parties or groups'},
{'A086': 'Voluntary work: Unpaid work local political action groups'},
{'A087': 'Voluntary work: Unpaid work human rights'},
{'A088': 'Voluntary work: Unpaid work environment, conservation, animal rights'},
{'A089': 'Voluntary work: Unpaid work professional associations'},
{'A090': 'Voluntary work: Unpaid work youth work'},
{'A091': 'Voluntary work: Unpaid work sports or recreation'},
{'A092': 'Voluntary work: Unpaid work women�s group'},
{'A093': 'Voluntary work: Unpaid work peace movement'},
{'A094': 'Voluntary work: Unpaid work organization concerned with health'},
{'A096': 'Voluntary work: Unpaid work other groups'},
{'A098': 'Active/Inactive membership of church or religious organization'},
{'A099': 'Active/Inactive membership of sport or recreation'},
{'A100': 'Active/Inactive membership of art, music, educational'},
{'A101': 'Active/Inactive membership of labour unions'},
{'A102': 'Active/Inactive membership of political party'},
{'A103': 'Active/Inactive membership of environmental organization'},
{'A104': 'Active/Inactive membership of professional organization'},
{'A105': 'Active/Inactive membership of charitable/humanitarian organization'},
{'A106': 'Active/Inactive membership of any other organization'},
{'A106B': 'Active/Inactive membership: Consumer organization'},
{'A106C': 'Active/Inactive membership: Self-help group, mutual aid group'},
{'A124_01': 'Neighbours: People with a criminal record'},
{'A124_02': 'Neighbours: People of a different race'},
{'A124_03': 'Neighbours: Heavy drinkers'},
{'A124_04': 'Neighbours: Emotionally unstable people'},
{'A124_05': 'Neighbours: Muslims'},
{'A124_06': 'Neighbours: Immigrants/foreign workers'},
{'A124_07': 'Neighbours: People who have AIDS'},
{'A124_08': 'Neighbours: Drug addicts'},
{'A124_09': 'Neighbours: Homosexuals'},
{'A124_10': 'Neighbours: Jews'},
{'A124_11': 'Neighbours: Evangelists'},
{'A124_12': 'Neighbours: People of a different religion'},
{'A124_14': 'Neighbours: Militant minority'},
{'A124_16': 'Neighbours: People not from country of origin'},
{'A124_17': 'Neighbours: Gypsies'},
{'A124_18': 'Neighbours: Political Extremists'},
{'A124_19': 'Neighbours: Trafficants'},
{'A124_24': 'Neighbours: Christians'},
{'A124_30': 'Neighbours: North-American persons'},
{'A124_34': 'Neighbours: Black people'},
{'A124_35': 'Neighbours: White people'},
{'A124_36': 'Neighbours: Coloured people'},
{'A124_37': 'Neighbours: Indians'},
{'A124_38': 'Neighbours: Kurds, Esids'},
{'A124_42': 'Neighbours: Unmarried couples living together'},
{'A124_43': 'Neighbours: People who speak a different language'},
{'A124_45': 'Neighbours: Sunnis'},
{'A124_46': 'Neighbours: Shia'},
{'A124_47': 'Neighbours: French'},
{'A124_48': 'Neighbours: British'},
{'A124_49': 'Neighbours: Iranian'},
{'A124_50': 'Neighbours: Kuwaiti'},
{'A124_51': 'Neighbours: Turkish'},
{'A124_52': 'Neighbours: Jordanian'},
{'A165': 'Most people can be trusted'},
{'A168': 'Do you think most people try to take advantage of you'},
{'A168A': 'Do you think most people try to take advantage of you (10 point scale)'},
{'A169': 'Good human relationships'},
{'A170': 'Satisfaction with your life'},
{'A173': 'How much freedom of choice and control'},
{'A189': 'Schwartz: It is important to this person to think up new ideas and be creative'},
{'A190': 'Schwartz: It is important to this person to be rich'},
{'A191': 'Schwartz: It is important to this person living in secure surroundings'},
{'A192': 'Schwartz: It is important to this person to have a good time'},
{'A193': 'Schwartz: It is important to this person to help the people nearby'},
{'A194': 'Schwartz: It is important to this person being very successful'},
{'A195': 'Schwartz: It is important to this person adventure and taking risks'},
{'A196': 'Schwartz: It is important to this person to always behave properly'},
{'A197': 'Schwartz: It is important to this person looking after the environment'},
{'A198': 'Schwartz: It is important to this person tradition'},
{'B001': 'Would give part of my income for the environment'},
{'B002': 'Increase in taxes if used to prevent environmental pollution'},
{'B003': 'Government should reduce environmental pollution'},
{'B008': 'Protecting environment vs. Economic growth'},
{'B009': 'Human & nature'},
{'B030': 'Past two years: given money to ecological organization'},
{'B031': 'Past two years: participated in demonstration for environment'},
{'C001': 'Jobs scarce: Men should have more right to a job than women (3 categories)'},
{'C001_01': 'Jobs scarce: Men should have more right to a job than women (5 categories)'},
{'C002': 'Jobs scarce: Employers should give priority to (nation) people than immigrants (3 categories)'},
{'C004': 'Jobs scarce: older people should be forced to retire'},
{'C006': 'Satisfaction with financial situation of household'},
{'C008': 'Work compared with Leisure'},
{'C009': 'First choice, if looking for a job'},
{'C010': 'Second choice if looking for a job'},
{'C011': 'Important in a job: good pay'},
{'C012': 'Important in a job: not too much pressure'},
{'C013': 'Important in a job: good job security'},
{'C014': 'Important in a job: a respected job'},
{'C015': 'Important in a job: good hours'},
{'C016': 'Important in a job: an opportunity to use initiative'},
{'C017': 'Important in a job: generous holidays'},
{'C018': 'Important in a job: that you can achieve something'},
{'C019': 'Important in a job: a responsible job'},
{'C020': 'Important in a job: a job that is interesting'},
{'C021': 'Important in a job: a job that meets one�s abilities'},
{'C036': 'To develop talents you need to have a job'},
{'C037': 'Humiliating to receive money without having to work for it'},
{'C038': 'People who don�t work turn lazy'},
{'C039': 'Work is a duty towards society'},
{'C040': 'People should not have to work if they don�t want to'},
{'C041': 'Work should come first even if it means less spare time'},
{'C059': 'Fairness: One secretary is paid more'},
{'C060': 'How business and industry should be managed'},
{'C061': 'Following instructions at work'},
{'D001_B': 'How much you trust: Your family (B)'},
{'D017': 'Ideal number of children'},
{'D018': 'Child needs a home with father and mother'},
{'D019': 'A woman has to have children to be fulfilled'},
{'D022': 'Marriage is an out-dated institution'},
{'D023': 'Woman as a single parent'},
{'D024': 'Enjoy sexual freedom'},
{'D025': 'If only one child allowed: boy or girl'},
{'D054': 'One of main goals in life has been to make my parents proud'},
{'D055': 'Make effort to live up to what my friends expect'},
{'D056': 'Relationship working mother'},
{'D057': 'Being a housewife just as fulfilling'},
{'D058': 'Husband and wife should both contribute to income'},
{'D059': 'Men make better political leaders than women do'},
{'D060': 'University is more important for a boy than for a girl'},
{'D061': 'Pre-school child suffers with working mother'},
{'D062': 'Women want a home and children'},
{'D066_B': 'Problem if women have more income than husband (3 categories)'},
{'D078': 'Men make better business executives than women do'},
{'E001': 'Aims of country: first choice'},
{'E002': 'Aims of country: second choice'},
{'E003': 'Aims of respondent: first choice'},
{'E004': 'Aims of respondent: second choice'},
{'E005': 'Most important: first choice'},
{'E006': 'Most important: second choice'},
{'E012': 'Willingness to fight for country'},
{'E014': 'Future changes: Less emphasis on money and material possessions'},
{'E015': 'Future changes: Less importance placed on work'},
{'E016': 'Future changes: More emphasis on technology'},
{'E018': 'Future changes: Greater respect for authority'},
{'E019': 'Future changes: More emphasis on family life'},
{'E022': 'Opinion about scientific advances'},
{'E023': 'Interest in politics'},
{'E025': 'Political action: Signing a petition'},
{'E025B': 'Political action recently done: signing a petition'},
{'E026': 'Political action: joining in boycotts'},
{'E026B': 'Political action recently done: joining in boycotts'},
{'E027': 'Political action: attending lawful/peaceful demonstrations'},
{'E028': 'Political action: joining unofficial strikes'},
{'E029': 'Political action: occupying buildings or factories'},
{'E033': 'Self positioning in political scale'},
{'E034': 'Basic kinds of attitudes concerning society'},
{'E035': 'Income equality'},
{'E036': 'Private vs state ownership of business'},
{'E037': 'Government responsibility'},
{'E038': 'Job taking of the unemployed'},
{'E039': 'Competition good or harmful'},
{'E040': 'Hard work brings success'},
{'E041': 'Wealth accumulation'},
{'E045': 'Major changes in life'},
{'E046': 'New and old ideas'},
{'E069_01': 'Confidence: Churches'},
{'E069_02': 'Confidence: Armed Forces'},
{'E069_03': 'Confidence: Education System'},
{'E069_04': 'Confidence: The Press'},
{'E069_05': 'Confidence: Labour Unions'},
{'E069_06': 'Confidence: The Police'},
{'E069_07': 'Confidence: Parliament'},
{'E069_08': 'Confidence: The Civil Services'},
{'E069_10': 'Confidence: Television'},
{'E069_11': 'Confidence: The Government'},
{'E069_12': 'Confidence: The Political Parties'},
{'E069_13': 'Confidence: Major Companies'},
{'E069_14': 'Confidence: The Environmental Protection Movement'},
{'E069_15': 'Confidence: The Women�s Movement'},
{'E069_17': 'Confidence: Justice System/Courts'},
{'E069_18': 'Confidence: The European Union'},
{'E069_18A': 'Confidence: Major regional organization (combined from country-specific)'},
{'E069_19': 'Confidence: NATO'},
{'E069_20': 'Confidence: The United Nations'},
{'E069_21': 'Confidence: The Arab League'},
{'E069_22': 'Confidence: The Association of South East Asian Nations -ASEAN'},
{'E069_23': 'Confidence: The Organization for African Unity-OAU'},
{'E069_24': 'Confidence: The NAFTA'},
{'E069_25': 'Confidence: The Andean pact'},
{'E069_26': 'Confidence: The Mercosur'},
{'E069_27': 'Confidence: The SAARC'},
{'E069_29': 'Confidence: The APEC'},
{'E069_30': 'Confidence: The Free Commerce Treaty (Tratado de libre comercio)'},
{'E069_31': 'Confidence: The United American States Organization (Organizaci�n de Estados Unidos Americanos - OEA)'},
{'E069_32': 'Confidence: The �Movimiento en pro de Vieques�(Puerto Rico)'},
{'E069_33': 'Confidence: Local/Regional Government'},
{'E069_40': 'Confidence: Charitable or humanitarian organizations'},
{'E069_41': 'Confidence: Banks'},
{'E069_42': 'Confidence: CARICOM'},
{'E069_43': 'Confidence: CIS'},
{'E069_44': 'Confidence: Confidence in CER with Australia'},
{'E069_54': 'Confidence: Universities'},
{'E069_55': 'Confidence: The Organization of the Islamic World'},
{'E069_56': 'Confidence: The Organization of American States (OAE)'},
{'E069_59': 'Confidence: Cooperation Council for the Arab states of Gulf (GCC)'},
{'E110': 'Satisfaction with the way democracy develops'},
{'E111': 'Rate political system for governing country'},
{'E112': 'Rate political system as it was before'},
{'E113': 'Rate political system in ten years'},
{'E114': 'Political system: Having a strong leader'},
{'E115': 'Political system: Having experts make decisions'},
{'E116': 'Political system: Having the army rule'},
{'E117': 'Political system: Having a democratic political system'},
{'E120': 'In democracy, the economic system runs badly'},
{'E121': 'Democracies are indecisive and have too much squabbling'},
{'E122': 'Democracies aren�t good at maintaining order'},
{'E123': 'Democracy may have problems but is better'},
{'E124': 'Respect for individual human rights nowadays'},
{'E125': 'Satisfaction with the people in national office'},
{'E128': 'Country is run by big interest vs. for all people�s benefit'},
{'E135': 'Who should decide: international peacekeeping'},
{'E136': 'Who should decide: protection of the environment'},
{'E137': 'Who should decide: aid to developing countries'},
{'E138': 'Who should decide: refugees'},
{'E139': 'Who should decide: human rights'},
{'E143': 'Immigrant policy'},
{'E179_WVS7LOC': 'Which party would you vote for if there were a national election tomorrow (Local names)'},
{'E179WVS': 'Which party would you vote for: first choice (WVS)'},
{'E180WVS': 'Which party would you vote for: second choice (WVS)'},
{'E182': 'Party that would never vote'},
{'E188': 'Frequency watches TV'},
{'E217': 'Science and technology are making our lives healthier, easier, and more comfortable'},
{'E218': 'Because of science and technology, there will be more opportunities for the next generation'},
{'E220': 'We depend too much on science and not enough on faith'},
{'E221B': 'Political action recently done: Attending peaceful/lawful demonstrations'},
{'E222': 'Political action: Other'},
{'E222B': 'Political action recently done: Other'},
{'E224': 'Democracy: Governments tax the rich and subsidize the poor.'},
{'E225': 'Democracy: Religious authorities interpret the laws.'},
{'E226': 'Democracy: People choose their leaders in free elections.'},
{'E227': 'Democracy: People receive state aid for unemployment.'},
{'E228': 'Democracy: The army takes over when government is incompetent.'},
{'E229': 'Democracy: Civil rights protect people�s liberty against oppression.'},
{'E233': 'Democracy: Women have the same rights as men.'},
{'E233A': "Democracy: The state makes people's incomes equal"},
{'E233B': 'Democracy: People obey their rulers'},
{'E234': 'The world is better off, or worse off, because of science and technology'},
{'E235': 'Importance of democracy'},
{'E236': 'Democraticness in own country'},
{'E238': 'Most serious problem of the world: 1st choice'},
{'E248': 'Information source: Daily newspaper'},
{'E248B': 'Information source: Daily newspaper (B)'},
{'E250': 'Information source: Printed magazines'},
{'E254': 'Information source: Talk with friends or colleagues'},
{'E254B': 'Information source: Talk with friends or colleagues (B)'},
{'E255': 'How often use of PC'},
{'E258B': 'Information source: TV news (B)'},
{'E259B': 'Information source: Radio news (B)'},
{'E260B': 'Information source: Mobile phone (B)'},
{'E261B': 'Information source: Email (B)'},
{'E262B': 'Information source: Internet (B)'},
{'E263': 'Vote in elections: local level'},
{'E264': 'Vote in elections: National level'},
{'E265_01': "How often in country's elections: Votes are counted fairly"},
{'E265_02': "How often in country's elections: Opposition candidates are prevented from running"},
{'E265_03': "How often in country's elections: TV news favors the governing party"},
{'E265_04': "How often in country's elections: Voters are bribed"},
{'E265_05': "How often in country's elections: Journalists provide fair coverage of elections"},
{'E265_06': "How often in country's elections: Election officials are fair"},
{'E265_07': "How often in country's elections: Rich people buy elections"},
{'E265_08': "How often in country's elections: Voters are threatened with  violence at the polls"},
{'E265_09': "How often in country's elections: Voters are offered a genuine choice in the elections"},
{'E266': 'Some people think that having honest elections makes a lot of difference in their lives;  other people think that it doesn�t matter much'},
{'F001': 'Thinking about meaning and purpose of life'},
{'F022': 'Statement: good and evil'},
{'F025': 'Religious denominations - major groups'},
{'F025_WVS': 'Religious denomination - detailed list'},
{'F025old': 'Religious denomination'},
{'F028': 'How often do you attend religious services'},
{'F028B': 'How often to you pray'},
{'F034': 'Religious person'},
{'F035': 'Churches give answers: moral problems'},
{'F036': 'Churches give answers: the problems of family life'},
{'F037': 'Churches give answers: people�s spiritual needs'},
{'F038': 'Churches give answers: the social problems'},
{'F049': 'Churches speak out on: government policy'},
{'F050': 'Believe in: God'},
{'F051': 'Believe in: life after death'},
{'F052': 'Believe in: people have a soul'},
{'F053': 'Believe in: hell'},
{'F054': 'Believe in: heaven'},
{'F055': 'Believe in: Sin'},
{'F057': 'Believe in: re-incarnation'},
{'F059': 'Believe in: devil'},
{'F062': 'Personal God vs. Spirit or Life Force'},
{'F063': 'How important is God in your life'},
{'F064': 'Get comfort and strength from religion'},
{'F065': 'Moments of prayer, meditation...'},
{'F102': 'Politicians who don�t believe in God are unfit for public office'},
{'F103': 'Religious leaders should not influence how people vote'},
{'F104': 'Better if more people with strong religious beliefs in public office'},
{'F105': 'Religious leaders should not influence government'},
{'F114A': 'Justifiable: Claiming government benefits to which you are not entitled'},
{'F114B': 'Justifiable: Stealing property'},
{'F114C': 'Justifiable: Parents beating children'},
{'F114D': 'Justifiable: Violence against other people'},
{'F115': 'Justifiable: Avoiding a fare on public transport'},
{'F116': 'Justifiable: Cheating on taxes'},
{'F117': 'Justifiable: Someone accepting a bribe'},
{'F118': 'Justifiable: Homosexuality'},
{'F119': 'Justifiable: Prostitution'},
{'F120': 'Justifiable: Abortion'},
{'F121': 'Justifiable: Divorce'},
{'F122': 'Justifiable: Euthanasia'},
{'F123': 'Justifiable: Suicide'},
{'F135A': 'Justifiable: Sex before marriage'},
{'F136': 'Justifiable: Political assassination'},
{'F139': 'Justifiable: Buy stolen goods'},
{'F144_02': 'Justifiable: Death penalty'},
{'F199': 'Justifiable: For a man to beat his wife'},
{'F200': 'Meaning of religion: To follow religious norms and ceremonies vs To do good to other people'},
{'F201': 'Meaning of religion: To make sense of life after death vs To make sense of life in this world'},
{'F202': 'Whenever science and religion conflict,  religion is always right'},
{'F203': 'The only acceptable religion  is my religion'},
{'G001': 'Geographical groups belonging to first'},
{'G001CS': 'Geographical groups belonging to first (country specific)'},
{'G002': 'Geographical groups belonging to second'},
{'G002CS': 'Geographical groups belonging to second  (country specific)'},
{'G006': 'How proud of nationality'},
{'G007_18_B': 'Trust: Your neighborhood (B)'},
{'G007_33_B': 'Trust: People you know personally (B)'},
{'G007_34_B': 'Trust: People you meet for the first time (B)'},
{'G007_35_B': 'Trust: People of another religion (B)'},
{'G007_36_B': 'Trust: People of another nationality (B)'},
{'G016': 'Language at home'},
{'G017': 'Born in this country: birth country'},
{'G018': 'When came to country'},
{'G019': 'I see myself as a world citizen'},
{'G020': 'I see myself as member of my local community'},
{'G021': 'I see myself as citizen of the [country] nation'},
{'G022A': 'I see myself as citizen of [Latinamerica]'},
{'G022B': 'I see myself as citizen of [North America]'},
{'G022C': 'I see myself as citizen of the [European Union]'},
{'G022D': 'I see myself as citizen of [APEC]'},
{'G022E': 'I see myself as citizen of [ASIA]'},
{'G022F': 'I see myself as citizen of [Mercosur]'},
{'G022K': 'I see myself as citizen of [The African Union]'},
{'G022L': 'I see myself as citizen of [Arab Maghreb Union]'},
{'G022M': 'I see myself as citizen of [ASEAN]'},
{'G022N': 'I see myself as citizen of [Arab Union]'},
{'G023': 'I see myself as an autonomous individual'},
{'G026': 'Mother immigrant'},
{'G027': 'Father immigrant'},
{'G027A': 'Respondent immigrant'},
{'G027B': 'Respondent citizen'},
{'H001': 'Secure in neighborhood'},
{'H002_01': 'Frequency in your neighborhood: Robberies'},
{'H002_02': 'Frequency in your neighborhood: Alcohol consumed in the streets'},
{'H002_03': 'Frequency in your neighborhood: Police or military interfere with people�s private life'},
{'H002_04': 'Frequency in your neighborhood: Racist behavior'},
{'H002_05': 'Frequency in your neighborhood: Drug sale in streets'},
{'H003_01': 'Things done for reasons of security: Didn�t carry much money'},
{'H003_02': 'Things done for reasons of security: Preferred not to go out at night'},
{'H003_03': 'Things done for reasons of security: Carried a knife, gun or other weapon'},
{'H004': 'Respondent was victim of a crime during the past year'},
{'H005': "Respondent's family was victim of a crime during last year"},
{'H006_01': 'Worries: Losing my job or not finding a job'},
{'H006_02': "Worries: Not being able to give one's children a good education"},
{'H006_03': 'Worries: A war involving my country'},
{'H006_04': 'Worries: A terrorist attack'},
{'H006_05': 'Worries: A civil war'},
{'H008_01': 'Frequency you/family (last 12 month): Gone without enough food to eat'},
{'H008_02': 'Frequency you/family (last 12 month): Felt unsafe from crime in your own home'},
{'H008_03': 'Frequency you/family (last 12 month): Gone without needed medicine or treatment that you needed'},
{'H008_04': 'Frequency you/family (last 12 month): Gone without a cash income'},
{'I001': 'One of the bad effects of science is that it breaks down people�s ideas of right and wrong'},
{'I002': 'It is not important for me to know about science in my daily life'},
{'MODE': 'Mode of data collection'},
{'PWGHT': 'Population size weight'},
{'S002VS': 'Chronology of EVS-WVS waves'},
{'S003': 'ISO 3166-1 numeric country code'},
{'S006': 'Original respondent number'},
{'S007': 'Unified respondent number'},
{'S008': 'Interviewer number'},
{'S010': 'Total length of interview'},
{'S011A': 'Time of the interview - Start'},
{'S011B': 'Time at the end of interview'},
{'S012': 'Date interview'},
{'S013': 'Respondent interested during the interview'},
{'S013B': 'Interview privacy'},
{'S016': 'Language of the interview (WVS/EVS list of languages)'},
{'S016B': 'Language in which interview was conducted'},
{'S017': 'Weight'},
{'S018': 'Equilibrated weight-1000'},
{'S020': 'Year survey'},
{'S021': 'Country - wave - study - set - year'},
{'S022': 'Year/month of start-fieldwork'},
{'S023': 'Year/month of end-fieldwork'},
{'S024': 'Country - wave'},
{'S025': 'Country - year'},
{'V001': 'Father born in country'},
{'V001A': 'Fathers country of birth - ISO 3166-1 code'},
{'V002': 'Mother born in country'},
{'V002A': 'Mothers country of birth - ISO 3166-1 code'},
{'V004AF_01': 'Highest educational level attained - Respondent�s Father ISCED'},
{'V004AM_01': 'Highest educational level attained - Respondent�s Mother ISCED'},
{'V004RF': 'Highest educational level attained - Respondent�s Father (Recoded)'},
{'V004RM': 'Highest educational level attained - Respondent�s Mother (Recoded)'},
{'V097EF': 'Respondent�s Father - Occupational group (when respondent was 14 years old) (WVS)'},
{'W002A_01': 'Highest educational level attained - Respondent�s Spouse ISCED'},
{'W002D': 'Country specific: Education level partner'},
{'W002R': 'educational level partner (recoded)'},
{'W003': 'Employment status - Responent�s Spouse'},
{'W006E': 'Respondent�s Spouse - Occupational group (WVS)'},
{'X001': 'Sex'},
{'X002': 'Year of birth'},
{'X002_02A': 'Respondents country of birth - ISO 3166-1 code'},
{'X003': 'Age'},
{'X003R': 'Age recoded (6 intervals)'},
{'X003R2': 'Age recoded (3 intervals)'},
{'X007': 'Marital status'},
{'X008': 'Have you been married before'},
{'X010': 'Where r lived after married'},
{'X011': 'How many children do you have'},
{'X011A': 'Have you had any children'},
{'X012': 'How many are still living at home'},
{'X013': 'Number of people in household'},
{'X023': 'What age did you complete your education'},
{'X023R': 'What age did you complete your education (recoded in intervals)'},
{'X024B': 'Respondent - literate'},
{'X025': 'Highest educational level attained'},
{'X025A_01': 'Highest educational level attained - Respondent ISCED-2011'},
{'X025CSWVS': 'Education (country specific)'},
{'X025LIT': 'Was the respondent literate'},
{'X025R': 'Education level (recoded)'},
{'X026': 'Do you live with your parents'},
{'X028': 'Employment status'},
{'X031': 'Are you supervising someone'},
{'X036': 'Profession/job'},
{'X036E': 'Respondent - Occupational group (WVS)'},
{'X040': 'Are you the chief wage earner in your house'},
{'X041': 'Is the chief wage earner employed now'},
{'X043': 'Chief wage earner profession/job'},
{'X044': 'Family savings during past year'},
{'X045': 'Social class (subjective)'},
{'X045B': 'Social class (subjective) with 6 categories'},
{'X046': 'Socio-economic status of respondent'},
{'X047_WVS': 'Scale of incomes'},
{'X047CS': 'Scale of incomes (Country specific)'},
{'X047R_WVS': 'Subjective income level (recoded in 3 groups)'},
{'X048ISO': 'Region ISO 3166-2'},
{'X048WVS': 'Region where the interview was conducted (WVS)'},
{'X049': 'Settlement size'},
{'X049A': 'Settlement size_5 groups'},
{'X049CS': 'Settlement size (country specific)'},
{'X050': 'Type of habitat'},
{'X050B': 'Settlement type where interview was conducted'},
{'X050C': 'Urban/Rural habitat'},
{'X051': 'Ethnic group'},
{'X052': 'Institution of occupation'},
{'X053': 'Nature of tasks: manual vs. Cognitive'},
{'X054': 'Nature of tasks: routine vs. Creative'},
{'X055': 'Nature of tasks: independence'},
]