country_info = [
    {"country_name": "Afghanistan", "country_2": "AF", "country_3": "AFG", "country_code": "4"},
    {"country_name": "Aland Islands", "country_2": "AX", "country_3": "ALA", "country_code": "248"},
    {"country_name": "Albania", "country_2": "AL", "country_3": "ALB", "country_code": "8"},
    {"country_name": "Algeria", "country_2": "DZ", "country_3": "DZA", "country_code": "12"},
    {"country_name": "American Samoa", "country_2": "AS", "country_3": "ASM", "country_code": "16"},
    {"country_name": "Andorra", "country_2": "AD", "country_3": "AND", "country_code": "20"},
    {"country_name": "Angola", "country_2": "AO", "country_3": "AGO", "country_code": "24"},
    {"country_name": "Anguilla", "country_2": "AI", "country_3": "AIA", "country_code": "660"},
    {"country_name": "Antarctica", "country_2": "AQ", "country_3": "ATA", "country_code": "10"},
    {"country_name": "Antigua and Barbuda", "country_2": "AG", "country_3": "ATG", "country_code": "28"},
    {"country_name": "Argentina", "country_2": "AR", "country_3": "ARG", "country_code": "32"},
    {"country_name": "Armenia", "country_2": "AM", "country_3": "ARM", "country_code": "51"},
    {"country_name": "Australia", "country_2": "AU", "country_3": "AUS", "country_code": "36"},
    {"country_name": "Austria", "country_2": "AT", "country_3": "AUT", "country_code": "40"},
    {"country_name": "Azerbaijan", "country_2": "AZ", "country_3": "AZE", "country_code": "31"},
    {"country_name": "Bahamas", "country_2": "BS", "country_3": "BHS", "country_code": "44"},
    {"country_name": "Bahrain", "country_2": "BH", "country_3": "BHR", "country_code": "48"},
    {"country_name": "Bangladesh", "country_2": "BD", "country_3": "BGD", "country_code": "50"},
    {"country_name": "Barbados", "country_2": "BB", "country_3": "BRB", "country_code": "52"},
    {"country_name": "Belarus", "country_2": "BY", "country_3": "BLR", "country_code": "112"},
    {"country_name": "Belgium", "country_2": "BE", "country_3": "BEL", "country_code": "56"},
    {"country_name": "Belize", "country_2": "BZ", "country_3": "BLZ", "country_code": "84"},
    {"country_name": "Benin", "country_2": "BJ", "country_3": "BEN", "country_code": "204"},
    {"country_name": "Bhutan", "country_2": "BT", "country_3": "BTN", "country_code": "64"},
    {"country_name": "Bolivia", "country_2": "BO", "country_3": "BOL", "country_code": "68"},
    {"country_name": "Bosnia and Herzegovina", "country_2": "BA", "country_3": "BIH", "country_code": "70"},
    {"country_name": "Botswana", "country_2": "BW", "country_3": "BWA", "country_code": "72"},
    {"country_name": "Brazil", "country_2": "BR", "country_3": "BRA", "country_code": "76"},
    {"country_name": "Bulgaria", "country_2": "BG", "country_3": "BGR", "country_code": "100"},
    {"country_name": "Burkina Faso", "country_2": "BF", "country_3": "BFA", "country_code": "854"},
    {"country_name": "Cambodia", "country_2": "KH", "country_3": "KHM", "country_code": "116"},
    {"country_name": "Cameroon", "country_2": "CM", "country_3": "CMR", "country_code": "120"},
    {"country_name": "Canada", "country_2": "CA", "country_3": "CAN", "country_code": "124"},
    {"country_name": "Chile", "country_2": "CL", "country_3": "CHL", "country_code": "152"},
    {"country_name": "China", "country_2": "CN", "country_3": "CHN", "country_code": "156"},
    {"country_name": "Colombia", "country_2": "CO", "country_3": "COL", "country_code": "170"},
    {"country_name": "Costa Rica", "country_2": "CR", "country_3": "CRI", "country_code": "188"},
    {"country_name": "Croatia", "country_2": "HR", "country_3": "HRV", "country_code": "191"},
    {"country_name": "Cuba", "country_2": "CU", "country_3": "CUB", "country_code": "192"},
    {"country_name": "Cyprus", "country_2": "CY", "country_3": "CYP", "country_code": "196"},
    {"country_name": "Czech Republic", "country_2": "CZ", "country_3": "CZE", "country_code": "203"},
    {"country_name": "Denmark", "country_2": "DK", "country_3": "DNK", "country_code": "208"},
    {"country_name": "Ecuador", "country_2": "EC", "country_3": "ECU", "country_code": "218"},
    {"country_name": "Egypt", "country_2": "EG", "country_3": "EGY", "country_code": "818"},
    {"country_name": "Estonia", "country_2": "EE", "country_3": "EST", "country_code": "233"},
    {"country_name": "Finland", "country_2": "FI", "country_3": "FIN", "country_code": "246"},
    {"country_name": "France", "country_2": "FR", "country_3": "FRA", "country_code": "250"},
    {"country_name": "Georgia", "country_2": "GE", "country_3": "GEO", "country_code": "268"},
    {"country_name": "Germany", "country_2": "DE", "country_3": "DEU", "country_code": "276"},
    {"country_name": "Greece", "country_2": "GR", "country_3": "GRC", "country_code": "300"},
    {"country_name": "Hong Kong", "country_2": "HK", "country_3": "HKG", "country_code": "344"},
    {"country_name": "Hungary", "country_2": "HU", "country_3": "HUN", "country_code": "348"},
    {"country_name": "India", "country_2": "IN", "country_3": "IND", "country_code": "356"},
    {"country_name": "Indonesia", "country_2": "ID", "country_3": "IDN", "country_code": "360"},
    {"country_name": "Iran", "country_2": "IR", "country_3": "IRN", "country_code": "364"},
    {"country_name": "Iraq", "country_2": "IQ", "country_3": "IRQ", "country_code": "368"},
    {"country_name": "Ireland", "country_2": "IE", "country_3": "IRL", "country_code": "372"},
    {"country_name": "Israel", "country_2": "IL", "country_3": "ISR", "country_code": "376"},
    {"country_name": "Italy", "country_2": "IT", "country_3": "ITA", "country_code": "380"},
    {"country_name": "Japan", "country_2": "JP", "country_3": "JPN", "country_code": "392"},
    {"country_name": "Jordan", "country_2": "JO", "country_3": "JOR", "country_code": "400"},
    {"country_name": "Kazakhstan", "country_2": "KZ", "country_3": "KAZ", "country_code": "398"},
    {"country_name": "Kenya", "country_2": "KE", "country_3": "KEN", "country_code": "404"},
    {"country_name": "Korea (North)", "country_2": "KP", "country_3": "PRK", "country_code": "408"},
    {"country_name": "Korea (South)", "country_2": "KR", "country_3": "KOR", "country_code": "410"},
    {"country_name": "Kuwait", "country_2": "KW", "country_3": "KWT", "country_code": "414"},
    {"country_name": "Kyrgyzstan", "country_2": "KG", "country_3": "KGZ", "country_code": "417"},
    {"country_name": "Latvia", "country_2": "LV", "country_3": "LVA", "country_code": "428"},
    {"country_name": "Lebanon", "country_2": "LB", "country_3": "LBN", "country_code": "422"},
    {"country_name": "Libya", "country_2": "LY", "country_3": "LBY", "country_code": "434"},
    {"country_name": "Lithuania", "country_2": "LT", "country_3": "LTU", "country_code": "440"},
    {"country_name": "Luxembourg", "country_2": "LU", "country_3": "LUX", "country_code": "442"},
    {"country_name": "Macedonia", "country_2": "MK", "country_3": "MKD", "country_code": "807"},
    {"country_name": "Madagascar", "country_2": "MG", "country_3": "MDG", "country_code": "450"},
    {"country_name": "Malawi", "country_2": "MW", "country_3": "MWI", "country_code": "454"},
    {"country_name": "Malaysia", "country_2": "MY", "country_3": "MYS", "country_code": "458"},
    {"country_name": "Maldives", "country_2": "MV", "country_3": "MDV", "country_code": "462"},
    {"country_name": "Mali", "country_2": "ML", "country_3": "MLI", "country_code": "466"},
    {"country_name": "Malta", "country_2": "MT", "country_3": "MLT", "country_code": "470"},
    {"country_name": "Mexico", "country_2": "MX", "country_3": "MEX", "country_code": "484"},
    {"country_name": "Moldova", "country_2": "MD", "country_3": "MDA", "country_code": "498"},
    {"country_name": "Mongolia", "country_2": "MN", "country_3": "MNG", "country_code": "496"},
    {"country_name": "Montenegro", "country_2": "ME", "country_3": "MNE", "country_code": "499"},
    {"country_name": "Morocco", "country_2": "MA", "country_3": "MAR", "country_code": "504"},
    {"country_name": "Myanmar", "country_2": "MM", "country_3": "MMR", "country_code": "104"},
    {"country_name": "Namibia", "country_2": "NA", "country_3": "NAM", "country_code": "516"},
    {"country_name": "Nepal", "country_2": "NP", "country_3": "NPL", "country_code": "524"},
    {"country_name": "Netherlands", "country_2": "NL", "country_3": "NLD", "country_code": "528"},
    {"country_name": "New Zealand", "country_2": "NZ", "country_3": "NZL", "country_code": "554"},
    {"country_name": "Nicaragua", "country_2": "NI", "country_3": "NIC", "country_code": "558"},
    {"country_name": "Niger", "country_2": "NE", "country_3": "NER", "country_code": "562"},
    {"country_name": "Nigeria", "country_2": "NG", "country_3": "NGA", "country_code": "566"},
    {"country_name": "Norway", "country_2": "NO", "country_3": "NOR", "country_code": "578"},
    {"country_name": "Pakistan", "country_2": "PK", "country_3": "PAK", "country_code": "586"},
    {"country_name": "Panama", "country_2": "PA", "country_3": "PAN", "country_code": "591"},
    {"country_name": "Paraguay", "country_2": "PY", "country_3": "PRY", "country_code": "600"},
    {"country_name": "Peru", "country_2": "PE", "country_3": "PER", "country_code": "604"},
    {"country_name": "Philippines", "country_2": "PH", "country_3": "PHL", "country_code": "608"},
    {"country_name": "Poland", "country_2": "PL", "country_3": "POL", "country_code": "616"},
    {"country_name": "Portugal", "country_2": "PT", "country_3": "PRT", "country_code": "620"},
    {"country_name": "Puerto Rico", "country_2": "PR", "country_3": "PRI", "country_code": "630"},
    {"country_name": "Qatar", "country_2": "QA", "country_3": "QAT", "country_code": "634"},
    {"country_name": "Romania", "country_2": "RO", "country_3": "ROU", "country_code": "642"},
    {"country_name": "Russian Federation", "country_2": "RU", "country_3": "RUS", "country_code": "643"},
    {"country_name": "Rwanda", "country_2": "RW", "country_3": "RWA", "country_code": "646"},
    {"country_name": "Saudi Arabia", "country_2": "SA", "country_3": "SAU", "country_code": "682"},
    {"country_name": "Serbia", "country_2": "RS", "country_3": "SRB", "country_code": "688"},
    {"country_name": "Singapore", "country_2": "SG", "country_3": "SGP", "country_code": "702"},
    {"country_name": "Slovakia", "country_2": "SK", "country_3": "SVK", "country_code": "703"},
    {"country_name": "Slovenia", "country_2": "SI", "country_3": "SVN", "country_code": "705"},
    {"country_name": "South Africa", "country_2": "ZA", "country_3": "ZAF", "country_code": "710"},
    {"country_name": "Spain", "country_2": "ES", "country_3": "ESP", "country_code": "724"},
    {"country_name": "Sri Lanka", "country_2": "LK", "country_3": "LKA", "country_code": "144"},
    {"country_name": "Sudan", "country_2": "SD", "country_3": "SDN", "country_code": "736"},
    {"country_name": "Sweden", "country_2": "SE", "country_3": "SWE", "country_code": "752"},
    {"country_name": "Switzerland", "country_2": "CH", "country_3": "CHE", "country_code": "756"},
    {"country_name": "Syrian Arab Republic", "country_2": "SY", "country_3": "SYR", "country_code": "760"},
    {"country_name": "Taiwan", "country_2": "TW", "country_3": "TWN", "country_code": "158"},
    {"country_name": "Tajikistan", "country_2": "TJ", "country_3": "TJK", "country_code": "762"},
    {"country_name": "Thailand", "country_2": "TH", "country_3": "THA", "country_code": "764"},
    {"country_name": "Togo", "country_2": "TG", "country_3": "TGO", "country_code": "768"},
    {"country_name": "Trinidad and Tobago", "country_2": "TT", "country_3": "TTO", "country_code": "780"},
    {"country_name": "Tunisia", "country_2": "TN", "country_3": "TUN", "country_code": "788"},
    {"country_name": "Turkey", "country_2": "TR", "country_3": "TUR", "country_code": "792"},
    {"country_name": "Turkmenistan", "country_2": "TM", "country_3": "TKM", "country_code": "795"},
    {"country_name": "Uganda", "country_2": "UG", "country_3": "UGA", "country_code": "800"},
    {"country_name": "Ukraine", "country_2": "UA", "country_3": "UKR", "country_code": "804"},
    {"country_name": "United Arab Emirates", "country_2": "AE", "country_3": "ARE", "country_code": "784"},
    {"country_name": "United Kingdom", "country_2": "GB", "country_3": "GBR", "country_code": "826"},
    {"country_name": "United States of America", "country_2": "US", "country_3": "USA", "country_code": "840"},
    {"country_name": "Uruguay", "country_2": "UY", "country_3": "URY", "country_code": "858"},
    {"country_name": "Uzbekistan", "country_2": "UZ", "country_3": "UZB", "country_code": "860"},
    {"country_name": "Venezuela", "country_2": "VE", "country_3": "VEN", "country_code": "862"},
    {"country_name": "Viet Nam", "country_2": "VN", "country_3": "VNM", "country_code": "704"},
    {"country_name": "Yemen", "country_2": "YE", "country_3": "YEM", "country_code": "887"},
    {"country_name": "Zambia", "country_2": "ZM", "country_3": "ZMB", "country_code": "894"},
    {"country_name": "Zimbabwe", "country_2": "ZW", "country_3": "ZWE", "country_code": "716"},
]
